// Generated from data/catalog_only_vehicles.json. Browse-only; no purchase authority.
using System;
using System.Collections.Generic;

namespace ALLIN1
{
    internal static class CatalogOnlyVehicles
    {
        internal const string Storage = "catalog_only";
        internal static readonly IReadOnlyDictionary<string, GbayVehicleRecord> Records =
            new Dictionary<string, GbayVehicleRecord>(StringComparer.OrdinalIgnoreCase)
            {
                { "alpha", new GbayVehicleRecord("allin1.online-content", "catalog-only", "alpha", "Alpha", "ALBANY", "sports", 0, Storage, "mpbusiness", 0, null, null, false, 1.0) },
                { "armytanker", new GbayVehicleRecord("allin1.online-content", "catalog-only", "armytanker", "Army Trailer", "", "service", 0, Storage, "base", 0, null, null, false, 1.0) },
                { "armytrailer", new GbayVehicleRecord("allin1.online-content", "catalog-only", "armytrailer", "Army Trailer", "", "service", 0, Storage, "base", 0, null, null, false, 1.0) },
                { "armytrailer2", new GbayVehicleRecord("allin1.online-content", "catalog-only", "armytrailer2", "Army Trailer", "", "service", 0, Storage, "base", 0, null, null, false, 1.0) },
                { "avenger2", new GbayVehicleRecord("allin1.online-content", "catalog-only", "avenger2", "Avenger", "MAMMOTH", "planes", 0, Storage, "mpchristmas2017", 0, null, null, false, 1.0) },
                { "avenger3", new GbayVehicleRecord("allin1.online-content", "catalog-only", "avenger3", "Avenger", "MAMMOTH", "planes", 0, Storage, "mp2023_01", 0, null, null, false, 1.0) },
                { "avenger4", new GbayVehicleRecord("allin1.online-content", "catalog-only", "avenger4", "Avenger", "MAMMOTH", "planes", 0, Storage, "mp2023_01", 0, null, null, false, 1.0) },
                { "baletrailer", new GbayVehicleRecord("allin1.online-content", "catalog-only", "baletrailer", "Baletrailer", "", "service", 0, Storage, "base", 0, null, null, false, 1.0) },
                { "barracks3", new GbayVehicleRecord("allin1.online-content", "catalog-only", "barracks3", "Barracks", "", "military", 0, Storage, "mpheist", 0, null, null, false, 1.0) },
                { "besra", new GbayVehicleRecord("allin1.online-content", "catalog-only", "besra", "Besra", "WESTERN", "planes", 0, Storage, "mppilot", 0, null, null, false, 1.0) },
                { "bifta", new GbayVehicleRecord("allin1.online-content", "catalog-only", "bifta", "Bifta", "BF", "offroad", 0, Storage, "mpbeach", 0, null, null, false, 1.0) },
                { "blade", new GbayVehicleRecord("allin1.online-content", "catalog-only", "blade", "Blade", "VAPID", "muscle", 0, Storage, "mphipster", 0, null, null, false, 1.0) },
                { "blimp", new GbayVehicleRecord("allin1.online-content", "catalog-only", "blimp", "Atomic Blimp", "", "planes", 0, Storage, "base", 0, null, null, false, 1.0) },
                { "blimp2", new GbayVehicleRecord("allin1.online-content", "catalog-only", "blimp2", "Xero Blimp", "", "planes", 0, Storage, "spupgrade", 0, null, null, false, 1.0) },
                { "blimp3", new GbayVehicleRecord("allin1.online-content", "catalog-only", "blimp3", "Blimp", "", "planes", 0, Storage, "mpbattle", 0, null, null, false, 1.0) },
                { "blista2", new GbayVehicleRecord("allin1.online-content", "catalog-only", "blista2", "Blista Compact", "DINKA", "sports", 0, Storage, "spupgrade", 0, null, null, false, 1.0) },
                { "blista3", new GbayVehicleRecord("allin1.online-content", "catalog-only", "blista3", "Go Go Monkey Blista", "DINKA", "sports", 0, Storage, "spupgrade", 0, null, null, false, 1.0) },
                { "boattrailer", new GbayVehicleRecord("allin1.online-content", "catalog-only", "boattrailer", "Boat Trailer", "", "service", 0, Storage, "base", 0, null, null, false, 1.0) },
                { "boattrailer2", new GbayVehicleRecord("allin1.online-content", "catalog-only", "boattrailer2", "Boat Trailer", "", "service", 0, Storage, "mp2023_02", 0, null, null, false, 1.0) },
                { "boattrailer3", new GbayVehicleRecord("allin1.online-content", "catalog-only", "boattrailer3", "Boat Trailer", "", "service", 0, Storage, "mp2023_02", 0, null, null, false, 1.0) },
                { "boxville5", new GbayVehicleRecord("allin1.online-content", "catalog-only", "boxville5", "Armored Boxville", "", "vans", 0, Storage, "mpimportexport", 0, null, null, false, 1.0) },
                { "brickade", new GbayVehicleRecord("allin1.online-content", "catalog-only", "brickade", "Brickade", "MTL", "service", 0, Storage, "mpexecutive", 0, null, null, false, 1.0) },
                { "brickade2", new GbayVehicleRecord("allin1.online-content", "catalog-only", "brickade2", "Brickade 6x6", "MTL", "service", 0, Storage, "mpchristmas3", 0, null, null, false, 1.0) },
                { "brigham", new GbayVehicleRecord("allin1.online-content", "catalog-only", "brigham", "Brigham", "ALBANY", "muscle", 0, Storage, "mp2023_01", 0, null, null, false, 1.0) },
                { "broadway", new GbayVehicleRecord("allin1.online-content", "catalog-only", "broadway", "Broadway", "CLASSIQUE", "muscle", 0, Storage, "mpchristmas3", 0, null, null, false, 1.0) },
                { "bruiser2", new GbayVehicleRecord("allin1.online-content", "catalog-only", "bruiser2", "Future Shock Bruiser", "BENEFAC", "offroad", 0, Storage, "mpchristmas2018", 0, null, null, false, 1.0) },
                { "bruiser3", new GbayVehicleRecord("allin1.online-content", "catalog-only", "bruiser3", "Nightmare Bruiser", "BENEFAC", "offroad", 0, Storage, "mpchristmas2018", 0, null, null, false, 1.0) },
                { "brutus2", new GbayVehicleRecord("allin1.online-content", "catalog-only", "brutus2", "Future Shock Brutus", "DECLASSE", "offroad", 0, Storage, "mpchristmas2018", 0, null, null, false, 1.0) },
                { "brutus3", new GbayVehicleRecord("allin1.online-content", "catalog-only", "brutus3", "Nightmare Brutus", "DECLASSE", "offroad", 0, Storage, "mpchristmas2018", 0, null, null, false, 1.0) },
                { "btype", new GbayVehicleRecord("allin1.online-content", "catalog-only", "btype", "Roosevelt", "ALBANY", "sportsclassics", 0, Storage, "mpvalentines", 0, null, null, false, 1.0) },
                { "btype2", new GbayVehicleRecord("allin1.online-content", "catalog-only", "btype2", "Fr\u00e4nken Stange", "ALBANY", "sportsclassics", 0, Storage, "mphalloween", 0, null, null, false, 1.0) },
                { "btype3", new GbayVehicleRecord("allin1.online-content", "catalog-only", "btype3", "Roosevelt Valor", "ALBANY", "sportsclassics", 0, Storage, "mpvalentines2", 0, null, null, false, 1.0) },
                { "buffalo3", new GbayVehicleRecord("allin1.online-content", "catalog-only", "buffalo3", "Sprunk Buffalo", "BRAVADO", "sports", 0, Storage, "spupgrade", 0, null, null, false, 1.0) },
                { "cablecar", new GbayVehicleRecord("allin1.online-content", "catalog-only", "cablecar", "Cable Car", "", "special", 0, Storage, "base", 0, null, null, false, 1.0) },
                { "caddy3", new GbayVehicleRecord("allin1.online-content", "catalog-only", "caddy3", "Caddy", "", "service", 0, Storage, "mpgunrunning", 0, null, null, false, 1.0) },
                { "calico", new GbayVehicleRecord("allin1.online-content", "catalog-only", "calico", "Calico GTF", "KARIN", "sports", 0, Storage, "mptuner", 0, null, null, false, 1.0) },
                { "cargobob4", new GbayVehicleRecord("allin1.online-content", "catalog-only", "cargobob4", "Cargobob", "", "helicopters", 0, Storage, "mpapartment", 0, null, null, false, 1.0) },
                { "cargoplane", new GbayVehicleRecord("allin1.online-content", "catalog-only", "cargoplane", "Cargo Plane", "", "planes", 0, Storage, "base", 0, null, null, false, 1.0) },
                { "cargoplane2", new GbayVehicleRecord("allin1.online-content", "catalog-only", "cargoplane2", "Cargo Plane", "", "planes", 0, Storage, "mpchristmas3", 0, null, null, false, 1.0) },
                { "cerberus", new GbayVehicleRecord("allin1.online-content", "catalog-only", "cerberus", "Apocalypse Cerberus", "MTL", "industrial", 0, Storage, "mpchristmas2018", 0, null, null, false, 1.0) },
                { "cerberus2", new GbayVehicleRecord("allin1.online-content", "catalog-only", "cerberus2", "Future Shock Cerberus", "MTL", "industrial", 0, Storage, "mpchristmas2018", 0, null, null, false, 1.0) },
                { "cerberus3", new GbayVehicleRecord("allin1.online-content", "catalog-only", "cerberus3", "Nightmare Cerberus", "MTL", "industrial", 0, Storage, "mpchristmas2018", 0, null, null, false, 1.0) },
                { "cheburek", new GbayVehicleRecord("allin1.online-content", "catalog-only", "cheburek", "Cheburek", "RUNE", "sportsclassics", 0, Storage, "mpassault", 0, null, null, false, 1.0) },
                { "coquette2", new GbayVehicleRecord("allin1.online-content", "catalog-only", "coquette2", "Coquette Classic", "INVERTO", "sportsclassics", 0, Storage, "mppilot", 0, null, null, false, 1.0) },
                { "cuban800", new GbayVehicleRecord("allin1.online-content", "catalog-only", "cuban800", "Cuban 800", "", "planes", 0, Storage, "base", 0, null, null, false, 1.0) },
                { "deathbike", new GbayVehicleRecord("allin1.online-content", "catalog-only", "deathbike", "Apocalypse Deathbike", "WESTERN", "motorcycles", 0, Storage, "mpchristmas2018", 0, null, null, false, 1.0) },
                { "deathbike2", new GbayVehicleRecord("allin1.online-content", "catalog-only", "deathbike2", "Future Shock Deathbike", "WESTERN", "motorcycles", 0, Storage, "mpchristmas2018", 0, null, null, false, 1.0) },
                { "deathbike3", new GbayVehicleRecord("allin1.online-content", "catalog-only", "deathbike3", "Nightmare Deathbike", "WESTERN", "motorcycles", 0, Storage, "mpchristmas2018", 0, null, null, false, 1.0) },
                { "dinghy3", new GbayVehicleRecord("allin1.online-content", "catalog-only", "dinghy3", "Dinghy", "NAGASAKI", "boats", 0, Storage, "mpheist", 0, null, null, false, 1.0) },
                { "dinghy4", new GbayVehicleRecord("allin1.online-content", "catalog-only", "dinghy4", "Dinghy", "NAGASAKI", "boats", 0, Storage, "mpapartment", 0, null, null, false, 1.0) },
                { "docktrailer", new GbayVehicleRecord("allin1.online-content", "catalog-only", "docktrailer", "DOCKTRAILER", "", "service", 0, Storage, "base", 0, null, null, false, 1.0) },
                { "dodo", new GbayVehicleRecord("allin1.online-content", "catalog-only", "dodo", "Dodo", "MAMMOTH", "planes", 0, Storage, "spupgrade", 0, null, null, false, 1.0) },
                { "dominator2", new GbayVehicleRecord("allin1.online-content", "catalog-only", "dominator2", "Pisswasser Dominator", "VAPID", "muscle", 0, Storage, "spupgrade", 0, null, null, false, 1.0) },
                { "dominator4", new GbayVehicleRecord("allin1.online-content", "catalog-only", "dominator4", "Apocalypse Dominator", "VAPID", "muscle", 0, Storage, "mpchristmas2018", 0, null, null, false, 1.0) },
                { "dominator5", new GbayVehicleRecord("allin1.online-content", "catalog-only", "dominator5", "Future Shock Dominator", "VAPID", "muscle", 0, Storage, "mpchristmas2018", 0, null, null, false, 1.0) },
                { "dominator6", new GbayVehicleRecord("allin1.online-content", "catalog-only", "dominator6", "Nightmare Dominator", "VAPID", "muscle", 0, Storage, "mpchristmas2018", 0, null, null, false, 1.0) },
                { "driftchavosv6", new GbayVehicleRecord("allin1.online-content", "catalog-only", "driftchavosv6", "Chavos V6", "DINKA", "sedans", 0, Storage, "mp2025_01", 0, null, null, false, 1.0) },
                { "driftcheburek", new GbayVehicleRecord("allin1.online-content", "catalog-only", "driftcheburek", "Cheburek", "RUNE", "sportsclassics", 0, Storage, "mp2024_02", 0, null, null, false, 1.0) },
                { "driftcoquette", new GbayVehicleRecord("allin1.online-content", "catalog-only", "driftcoquette", "DRIFTCOQUE", "INVERTO", "sports", 0, Storage, "mp2026_01", 0, null, null, false, 1.0) },
                { "driftcypher", new GbayVehicleRecord("allin1.online-content", "catalog-only", "driftcypher", "Cypher", "UBERMACHT", "sports", 0, Storage, "mp2024_01", 0, null, null, false, 1.0) },
                { "driftdominator10", new GbayVehicleRecord("allin1.online-content", "catalog-only", "driftdominator10", "Dominator FX", "VAPID", "muscle", 0, Storage, "mp2025_01", 0, null, null, false, 1.0) },
                { "driftdominator8", new GbayVehicleRecord("allin1.online-content", "catalog-only", "driftdominator8", "DRIFTDOM8", "VAPID", "muscle", 0, Storage, "mp2026_01", 0, null, null, false, 1.0) },
                { "driftdominator9", new GbayVehicleRecord("allin1.online-content", "catalog-only", "driftdominator9", "Dominator GT", "VAPID", "muscle", 0, Storage, "mp2025_02", 0, null, null, false, 1.0) },
                { "driftelegy", new GbayVehicleRecord("allin1.online-content", "catalog-only", "driftelegy", "DRIFTELEGY", "ANNIS", "sports", 0, Storage, "mp2026_01", 0, null, null, false, 1.0) },
                { "drifteuros", new GbayVehicleRecord("allin1.online-content", "catalog-only", "drifteuros", "Euros", "ANNIS", "sports", 0, Storage, "mp2023_02", 0, null, null, false, 1.0) },
                { "driftfr36", new GbayVehicleRecord("allin1.online-content", "catalog-only", "driftfr36", "FR36", "FATHOM", "coupes", 0, Storage, "mp2023_02", 0, null, null, false, 1.0) },
                { "driftfuto", new GbayVehicleRecord("allin1.online-content", "catalog-only", "driftfuto", "Futo GTX", "KARIN", "sports", 0, Storage, "mp2023_02", 0, null, null, false, 1.0) },
                { "driftfuto2", new GbayVehicleRecord("allin1.online-content", "catalog-only", "driftfuto2", "Futo", "KARIN", "sports", 0, Storage, "mp2024_02", 0, null, null, false, 1.0) },
                { "driftgauntlet4", new GbayVehicleRecord("allin1.online-content", "catalog-only", "driftgauntlet4", "Gauntlet Hellfire", "BRAVADO", "muscle", 0, Storage, "mp2025_01", 0, null, null, false, 1.0) },
                { "drifthardy", new GbayVehicleRecord("allin1.online-content", "catalog-only", "drifthardy", "Hardy", "ANNIS", "sedans", 0, Storage, "mp2025_01", 0, null, null, false, 1.0) },
                { "driftjester", new GbayVehicleRecord("allin1.online-content", "catalog-only", "driftjester", "Jester RR", "DINKA", "sports", 0, Storage, "mp2023_02", 0, null, null, false, 1.0) },
                { "driftjester3", new GbayVehicleRecord("allin1.online-content", "catalog-only", "driftjester3", "Jester Classic", "DINKA", "sportsclassics", 0, Storage, "mp2024_02", 0, null, null, false, 1.0) },
                { "driftkeitora", new GbayVehicleRecord("allin1.online-content", "catalog-only", "driftkeitora", "Keitora", "SHITZU", "service", 0, Storage, "mp2025_02", 0, null, null, false, 1.0) },
                { "driftl352", new GbayVehicleRecord("allin1.online-content", "catalog-only", "driftl352", "Drift Walton L35", "DECLASSE", "offroad", 0, Storage, "mp2025_01", 0, null, null, false, 1.0) },
                { "driftnebula", new GbayVehicleRecord("allin1.online-content", "catalog-only", "driftnebula", "Nebula Turbo", "VULCAR", "sportsclassics", 0, Storage, "mp2024_01", 0, null, null, false, 1.0) },
                { "driftremus", new GbayVehicleRecord("allin1.online-content", "catalog-only", "driftremus", "Remus", "ANNIS", "sports", 0, Storage, "mp2023_02", 0, null, null, false, 1.0) },
                { "driftrt3000", new GbayVehicleRecord("allin1.online-content", "catalog-only", "driftrt3000", "RT3000", "DINKA", "sports", 0, Storage, "mp2025_02", 0, null, null, false, 1.0) },
                { "driftsentinel", new GbayVehicleRecord("allin1.online-content", "catalog-only", "driftsentinel", "Sentinel Classic Widebody", "UBERMACH", "sports", 0, Storage, "mp2024_01", 0, null, null, false, 1.0) },
                { "driftsentinel2", new GbayVehicleRecord("allin1.online-content", "catalog-only", "driftsentinel2", "Sentinel XS", "UBERMACH", "coupes", 0, Storage, "mp2025_02", 0, null, null, false, 1.0) },
                { "drifttampa", new GbayVehicleRecord("allin1.online-content", "catalog-only", "drifttampa", "Drift Tampa", "DECLASSE", "sports", 0, Storage, "mp2023_02", 0, null, null, false, 1.0) },
                { "driftvorschlag", new GbayVehicleRecord("allin1.online-content", "catalog-only", "driftvorschlag", "Vorschlaghammer", "BENEFACTOR", "sedans", 0, Storage, "mp2024_01", 0, null, null, false, 1.0) },
                { "driftyosemite", new GbayVehicleRecord("allin1.online-content", "catalog-only", "driftyosemite", "Drift Yosemite", "DECLASSE", "muscle", 0, Storage, "mp2023_02", 0, null, null, false, 1.0) },
                { "driftzr350", new GbayVehicleRecord("allin1.online-content", "catalog-only", "driftzr350", "ZR350", "ANNIS", "sports", 0, Storage, "mp2023_02", 0, null, null, false, 1.0) },
                { "dubsta3", new GbayVehicleRecord("allin1.online-content", "catalog-only", "dubsta3", "Dubsta 6x6", "BENEFAC", "offroad", 0, Storage, "mphipster", 0, null, null, false, 1.0) },
                { "dukes", new GbayVehicleRecord("allin1.online-content", "catalog-only", "dukes", "Dukes", "IMPONTE", "muscle", 0, Storage, "spupgrade", 0, null, null, false, 1.0) },
                { "dukes2", new GbayVehicleRecord("allin1.online-content", "catalog-only", "dukes2", "Duke O'Death", "IMPONTE", "muscle", 0, Storage, "spupgrade", 0, null, null, false, 1.0) },
                { "dune4", new GbayVehicleRecord("allin1.online-content", "catalog-only", "dune4", "Ramp Buggy", "", "offroad", 0, Storage, "mpimportexport", 0, null, null, false, 1.0) },
                { "duster", new GbayVehicleRecord("allin1.online-content", "catalog-only", "duster", "Duster", "", "planes", 0, Storage, "base", 0, null, null, false, 1.0) },
                { "dynasty", new GbayVehicleRecord("allin1.online-content", "catalog-only", "dynasty", "Dynasty", "WEENY", "sportsclassics", 0, Storage, "mpvinewood", 0, null, null, false, 1.0) },
                { "eudora", new GbayVehicleRecord("allin1.online-content", "catalog-only", "eudora", "Eudora", "WILLARD", "muscle", 0, Storage, "mpchristmas3", 0, null, null, false, 1.0) },
                { "fagaloa", new GbayVehicleRecord("allin1.online-content", "catalog-only", "fagaloa", "Fagaloa", "VULCAR", "sportsclassics", 0, Storage, "mpassault", 0, null, null, false, 1.0) },
                { "freight", new GbayVehicleRecord("allin1.online-content", "catalog-only", "freight", "Freight Train", "", "special", 0, Storage, "base", 0, null, null, false, 1.0) },
                { "freight2", new GbayVehicleRecord("allin1.online-content", "catalog-only", "freight2", "Freight Train", "", "special", 0, Storage, "mp2023_02", 0, null, null, false, 1.0) },
                { "freightcar", new GbayVehicleRecord("allin1.online-content", "catalog-only", "freightcar", "Freight Train", "", "special", 0, Storage, "base", 0, null, null, false, 1.0) },
                { "freightcar2", new GbayVehicleRecord("allin1.online-content", "catalog-only", "freightcar2", "Freight Train", "", "special", 0, Storage, "mptuner", 0, null, null, false, 1.0) },
                { "freightcar3", new GbayVehicleRecord("allin1.online-content", "catalog-only", "freightcar3", "Freight Train", "", "special", 0, Storage, "mp2024_02", 0, null, null, false, 1.0) },
                { "freightcont1", new GbayVehicleRecord("allin1.online-content", "catalog-only", "freightcont1", "Freight Train", "", "special", 0, Storage, "base", 0, null, null, false, 1.0) },
                { "freightcont2", new GbayVehicleRecord("allin1.online-content", "catalog-only", "freightcont2", "Freight Train", "", "special", 0, Storage, "base", 0, null, null, false, 1.0) },
                { "freightgrain", new GbayVehicleRecord("allin1.online-content", "catalog-only", "freightgrain", "Freight Train", "", "special", 0, Storage, "base", 0, null, null, false, 1.0) },
                { "freighttrailer", new GbayVehicleRecord("allin1.online-content", "catalog-only", "freighttrailer", "FREIGHTTRAILER", "", "service", 0, Storage, "base", 0, null, null, false, 1.0) },
                { "furoregt", new GbayVehicleRecord("allin1.online-content", "catalog-only", "furoregt", "Furore GT", "LAMPADA", "sports", 0, Storage, "mplts", 0, null, null, false, 1.0) },
                { "gauntlet2", new GbayVehicleRecord("allin1.online-content", "catalog-only", "gauntlet2", "Redwood Gauntlet", "BRAVADO", "muscle", 0, Storage, "spupgrade", 0, null, null, false, 1.0) },
                { "gburrito2", new GbayVehicleRecord("allin1.online-content", "catalog-only", "gburrito2", "Gang Burrito", "DECLASSE", "vans", 0, Storage, "mpheist", 0, null, null, false, 1.0) },
                { "glendale", new GbayVehicleRecord("allin1.online-content", "catalog-only", "glendale", "Glendale", "BENEFAC", "sedans", 0, Storage, "mphipster", 0, null, null, false, 1.0) },
                { "graintrailer", new GbayVehicleRecord("allin1.online-content", "catalog-only", "graintrailer", "Graintrailer", "", "service", 0, Storage, "base", 0, null, null, false, 1.0) },
                { "greenwood", new GbayVehicleRecord("allin1.online-content", "catalog-only", "greenwood", "Greenwood", "BRAVADO", "muscle", 0, Storage, "mpsum2", 0, null, null, false, 1.0) },
                { "hakuchou", new GbayVehicleRecord("allin1.online-content", "catalog-only", "hakuchou", "Hakuchou", "SHITZU", "motorcycles", 0, Storage, "mplts", 0, null, null, false, 1.0) },
                { "huntley", new GbayVehicleRecord("allin1.online-content", "catalog-only", "huntley", "Huntley S", "ENUS", "suvs", 0, Storage, "mpbusiness2", 0, null, null, false, 1.0) },
                { "ignus2", new GbayVehicleRecord("allin1.online-content", "catalog-only", "ignus2", "Weaponized Ignus", "PEGASSI", "super", 0, Storage, "mpg9ec", 0, null, null, false, 1.0) },
                { "impaler2", new GbayVehicleRecord("allin1.online-content", "catalog-only", "impaler2", "Apocalypse Impaler", "DECLASSE", "muscle", 0, Storage, "mpchristmas2018", 0, null, null, false, 1.0) },
                { "impaler3", new GbayVehicleRecord("allin1.online-content", "catalog-only", "impaler3", "Future Shock Impaler", "DECLASSE", "muscle", 0, Storage, "mpchristmas2018", 0, null, null, false, 1.0) },
                { "impaler4", new GbayVehicleRecord("allin1.online-content", "catalog-only", "impaler4", "Nightmare Impaler", "DECLASSE", "muscle", 0, Storage, "mpchristmas2018", 0, null, null, false, 1.0) },
                { "imperator2", new GbayVehicleRecord("allin1.online-content", "catalog-only", "imperator2", "Future Shock Imperator", "VAPID", "muscle", 0, Storage, "mpchristmas2018", 0, null, null, false, 1.0) },
                { "imperator3", new GbayVehicleRecord("allin1.online-content", "catalog-only", "imperator3", "Nightmare Imperator", "VAPID", "muscle", 0, Storage, "mpchristmas2018", 0, null, null, false, 1.0) },
                { "innovation", new GbayVehicleRecord("allin1.online-content", "catalog-only", "innovation", "Innovation", "LCC", "motorcycles", 0, Storage, "mplts", 0, null, null, false, 1.0) },
                { "insurgent2", new GbayVehicleRecord("allin1.online-content", "catalog-only", "insurgent2", "Insurgent", "HVY", "offroad", 0, Storage, "mpheist", 0, null, null, false, 1.0) },
                { "issi4", new GbayVehicleRecord("allin1.online-content", "catalog-only", "issi4", "Apocalypse Issi", "WEENY", "compacts", 0, Storage, "mpchristmas2018", 0, null, null, false, 1.0) },
                { "issi5", new GbayVehicleRecord("allin1.online-content", "catalog-only", "issi5", "Future Shock Issi", "WEENY", "compacts", 0, Storage, "mpchristmas2018", 0, null, null, false, 1.0) },
                { "issi6", new GbayVehicleRecord("allin1.online-content", "catalog-only", "issi6", "Nightmare Issi", "WEENY", "compacts", 0, Storage, "mpchristmas2018", 0, null, null, false, 1.0) },
                { "jester", new GbayVehicleRecord("allin1.online-content", "catalog-only", "jester", "Jester", "DINKA", "sports", 0, Storage, "mpbusiness", 0, null, null, false, 1.0) },
                { "jester2", new GbayVehicleRecord("allin1.online-content", "catalog-only", "jester2", "Jester (Racecar)", "DINKA", "sports", 0, Storage, "mpchristmas2", 0, null, null, false, 1.0) },
                { "jet", new GbayVehicleRecord("allin1.online-content", "catalog-only", "jet", "Jet", "", "planes", 0, Storage, "base", 0, null, null, false, 1.0) },
                { "kalahari", new GbayVehicleRecord("allin1.online-content", "catalog-only", "kalahari", "Kalahari", "CANIS", "offroad", 0, Storage, "mpbeach", 0, null, null, false, 1.0) },
                { "kosatka", new GbayVehicleRecord("allin1.online-content", "catalog-only", "kosatka", "Kosatka", "RUNE", "boats", 0, Storage, "mpheist4", 0, null, null, false, 1.0) },
                { "lazer", new GbayVehicleRecord("allin1.online-content", "catalog-only", "lazer", "P-996 LAZER", "", "planes", 0, Storage, "base", 0, null, null, false, 1.0) },
                { "lurcher", new GbayVehicleRecord("allin1.online-content", "catalog-only", "lurcher", "Lurcher", "ALBANY", "muscle", 0, Storage, "mphalloween", 0, null, null, false, 1.0) },
                { "luxor", new GbayVehicleRecord("allin1.online-content", "catalog-only", "luxor", "Luxor", "BUCKING", "planes", 0, Storage, "base", 0, null, null, false, 1.0) },
                { "mammatus", new GbayVehicleRecord("allin1.online-content", "catalog-only", "mammatus", "Mammatus", "", "planes", 0, Storage, "base", 0, null, null, false, 1.0) },
                { "marshall", new GbayVehicleRecord("allin1.online-content", "catalog-only", "marshall", "Marshall", "CHEVAL", "offroad", 0, Storage, "spupgrade", 0, null, null, false, 1.0) },
                { "massacro", new GbayVehicleRecord("allin1.online-content", "catalog-only", "massacro", "Massacro", "DEWBAUCH", "sports", 0, Storage, "mpbusiness2", 0, null, null, false, 1.0) },
                { "massacro2", new GbayVehicleRecord("allin1.online-content", "catalog-only", "massacro2", "Massacro (Racecar)", "DEWBAUCH", "sports", 0, Storage, "mpchristmas2", 0, null, null, false, 1.0) },
                { "metrotrain", new GbayVehicleRecord("allin1.online-content", "catalog-only", "metrotrain", "Freight Train", "", "special", 0, Storage, "base", 0, null, null, false, 1.0) },
                { "miljet", new GbayVehicleRecord("allin1.online-content", "catalog-only", "miljet", "Miljet", "BUCKING", "planes", 0, Storage, "mppilot", 0, null, null, false, 1.0) },
                { "minitank", new GbayVehicleRecord("allin1.online-content", "catalog-only", "minitank", "Invade and Persuade Tank", "", "military", 0, Storage, "mpheist3", 0, null, null, false, 1.0) },
                { "monster", new GbayVehicleRecord("allin1.online-content", "catalog-only", "monster", "Monster", "VAPID", "offroad", 0, Storage, "mpindependence", 0, null, null, false, 1.0) },
                { "monster4", new GbayVehicleRecord("allin1.online-content", "catalog-only", "monster4", "Future Shock Sasquatch", "BRAVADO", "offroad", 0, Storage, "mpchristmas2018", 0, null, null, false, 1.0) },
                { "monster5", new GbayVehicleRecord("allin1.online-content", "catalog-only", "monster5", "Nightmare Sasquatch", "BRAVADO", "offroad", 0, Storage, "mpchristmas2018", 0, null, null, false, 1.0) },
                { "mule5", new GbayVehicleRecord("allin1.online-content", "catalog-only", "mule5", "Mule", "MAIBATSU", "industrial", 0, Storage, "mpsecurity", 0, null, null, false, 1.0) },
                { "panto", new GbayVehicleRecord("allin1.online-content", "catalog-only", "panto", "Panto", "BENEFAC", "compacts", 0, Storage, "mphipster", 0, null, null, false, 1.0) },
                { "paradise", new GbayVehicleRecord("allin1.online-content", "catalog-only", "paradise", "Paradise", "BRAVADO", "vans", 0, Storage, "mpbeach", 0, null, null, false, 1.0) },
                { "patriot2", new GbayVehicleRecord("allin1.online-content", "catalog-only", "patriot2", "Patriot Stretch", "MAMMOTH", "suvs", 0, Storage, "mpbattle", 0, null, null, false, 1.0) },
                { "peyote3", new GbayVehicleRecord("allin1.online-content", "catalog-only", "peyote3", "Peyote Custom", "VAPID", "sportsclassics", 0, Storage, "mpsum", 0, null, null, false, 1.0) },
                { "phantom4", new GbayVehicleRecord("allin1.online-content", "catalog-only", "phantom4", "Phantom", "JOBUILT", "industrial", 0, Storage, "mp2023_02", 0, null, null, false, 1.0) },
                { "pigalle", new GbayVehicleRecord("allin1.online-content", "catalog-only", "pigalle", "Pigalle", "LAMPADA", "sportsclassics", 0, Storage, "mphipster", 0, null, null, false, 1.0) },
                { "proptrailer", new GbayVehicleRecord("allin1.online-content", "catalog-only", "proptrailer", "proptrailer", "", "service", 0, Storage, "base", 0, null, null, false, 1.0) },
                { "raketrailer", new GbayVehicleRecord("allin1.online-content", "catalog-only", "raketrailer", "Trailer", "", "service", 0, Storage, "base", 0, null, null, false, 1.0) },
                { "ratbike", new GbayVehicleRecord("allin1.online-content", "catalog-only", "ratbike", "Rat Bike", "WESTERN", "motorcycles", 0, Storage, "mpbiker", 0, null, null, false, 1.0) },
                { "ratloader2", new GbayVehicleRecord("allin1.online-content", "catalog-only", "ratloader2", "Rat-Truck", "BRAVADO", "muscle", 0, Storage, "mpchristmas2", 0, null, null, false, 1.0) },
                { "rcbandito", new GbayVehicleRecord("allin1.online-content", "catalog-only", "rcbandito", "RC Bandito", "", "offroad", 0, Storage, "mpchristmas2018", 0, null, null, false, 1.0) },
                { "retinue2", new GbayVehicleRecord("allin1.online-content", "catalog-only", "retinue2", "Retinue Mk II", "VAPID", "sportsclassics", 0, Storage, "mpheist3", 0, null, null, false, 1.0) },
                { "rhapsody", new GbayVehicleRecord("allin1.online-content", "catalog-only", "rhapsody", "Rhapsody", "DECLASSE", "compacts", 0, Storage, "mphipster", 0, null, null, false, 1.0) },
                { "ruiner3", new GbayVehicleRecord("allin1.online-content", "catalog-only", "ruiner3", "Ruiner", "IMPONTE", "muscle", 0, Storage, "mpimportexport", 0, null, null, false, 1.0) },
                { "sanctus", new GbayVehicleRecord("allin1.online-content", "catalog-only", "sanctus", "Sanctus", "LCC", "motorcycles", 0, Storage, "mpbiker", 0, null, null, false, 1.0) },
                { "scarab2", new GbayVehicleRecord("allin1.online-content", "catalog-only", "scarab2", "Future Shock Scarab", "HVY", "military", 0, Storage, "mpchristmas2018", 0, null, null, false, 1.0) },
                { "scarab3", new GbayVehicleRecord("allin1.online-content", "catalog-only", "scarab3", "Nightmare Scarab", "HVY", "military", 0, Storage, "mpchristmas2018", 0, null, null, false, 1.0) },
                { "seashark3", new GbayVehicleRecord("allin1.online-content", "catalog-only", "seashark3", "Seashark", "SPEEDOPH", "boats", 0, Storage, "mpapartment", 0, null, null, false, 1.0) },
                { "seasparrow", new GbayVehicleRecord("allin1.online-content", "catalog-only", "seasparrow", "Sea Sparrow", "", "helicopters", 0, Storage, "mpassault", 0, null, null, false, 1.0) },
                { "seasparrow2", new GbayVehicleRecord("allin1.online-content", "catalog-only", "seasparrow2", "Sparrow", "", "helicopters", 0, Storage, "mpheist4", 0, null, null, false, 1.0) },
                { "seasparrow3", new GbayVehicleRecord("allin1.online-content", "catalog-only", "seasparrow3", "Sparrow", "", "helicopters", 0, Storage, "mpheist4", 0, null, null, false, 1.0) },
                { "shamal", new GbayVehicleRecord("allin1.online-content", "catalog-only", "shamal", "Shamal", "BUCKING", "planes", 0, Storage, "base", 0, null, null, false, 1.0) },
                { "slamvan", new GbayVehicleRecord("allin1.online-content", "catalog-only", "slamvan", "Slamvan", "VAPID", "muscle", 0, Storage, "mpchristmas2", 0, null, null, false, 1.0) },
                { "slamvan3", new GbayVehicleRecord("allin1.online-content", "catalog-only", "slamvan3", "Slamvan Custom", "VAPID", "muscle", 0, Storage, "mplowrider2", 0, null, null, false, 1.0) },
                { "slamvan4", new GbayVehicleRecord("allin1.online-content", "catalog-only", "slamvan4", "Apocalypse Slamvan", "VAPID", "muscle", 0, Storage, "mpchristmas2018", 0, null, null, false, 1.0) },
                { "slamvan5", new GbayVehicleRecord("allin1.online-content", "catalog-only", "slamvan5", "Future Shock Slamvan", "VAPID", "muscle", 0, Storage, "mpchristmas2018", 0, null, null, false, 1.0) },
                { "slamvan6", new GbayVehicleRecord("allin1.online-content", "catalog-only", "slamvan6", "Nightmare Slamvan", "VAPID", "muscle", 0, Storage, "mpchristmas2018", 0, null, null, false, 1.0) },
                { "sovereign", new GbayVehicleRecord("allin1.online-content", "catalog-only", "sovereign", "Sovereign", "WESTERN", "motorcycles", 0, Storage, "mpindependence", 0, null, null, false, 1.0) },
                { "speeder", new GbayVehicleRecord("allin1.online-content", "catalog-only", "speeder", "Speeder", "PEGASSI", "boats", 0, Storage, "mpbeach", 0, null, null, false, 1.0) },
                { "speeder2", new GbayVehicleRecord("allin1.online-content", "catalog-only", "speeder2", "Speeder", "PEGASSI", "boats", 0, Storage, "mpapartment", 0, null, null, false, 1.0) },
                { "speedo5", new GbayVehicleRecord("allin1.online-content", "catalog-only", "speedo5", "Speedo Custom", "VAPID", "vans", 0, Storage, "mp2023_01", 0, null, null, false, 1.0) },
                { "stalion", new GbayVehicleRecord("allin1.online-content", "catalog-only", "stalion", "Stallion", "DECLASSE", "muscle", 0, Storage, "spupgrade", 0, null, null, false, 1.0) },
                { "stalion2", new GbayVehicleRecord("allin1.online-content", "catalog-only", "stalion2", "Burger Shot Stallion", "DECLASSE", "muscle", 0, Storage, "spupgrade", 0, null, null, false, 1.0) },
                { "stunt", new GbayVehicleRecord("allin1.online-content", "catalog-only", "stunt", "Mallard", "", "planes", 0, Storage, "base", 0, null, null, false, 1.0) },
                { "submersible", new GbayVehicleRecord("allin1.online-content", "catalog-only", "submersible", "Submersible", "", "boats", 0, Storage, "base", 0, null, null, false, 1.0) },
                { "submersible2", new GbayVehicleRecord("allin1.online-content", "catalog-only", "submersible2", "Kraken", "", "boats", 0, Storage, "spupgrade", 0, null, null, false, 1.0) },
                { "swift", new GbayVehicleRecord("allin1.online-content", "catalog-only", "swift", "Swift", "BUCKING", "helicopters", 0, Storage, "mppilot", 0, null, null, false, 1.0) },
                { "tanker", new GbayVehicleRecord("allin1.online-content", "catalog-only", "tanker", "Trailer", "", "service", 0, Storage, "base", 0, null, null, false, 1.0) },
                { "tanker2", new GbayVehicleRecord("allin1.online-content", "catalog-only", "tanker2", "TANKER", "", "service", 0, Storage, "mpheist", 0, null, null, false, 1.0) },
                { "tankercar", new GbayVehicleRecord("allin1.online-content", "catalog-only", "tankercar", "Freight Train", "", "special", 0, Storage, "base", 0, null, null, false, 1.0) },
                { "technical2", new GbayVehicleRecord("allin1.online-content", "catalog-only", "technical2", "Technical Aqua", "KARIN", "offroad", 0, Storage, "mpimportexport", 0, null, null, false, 1.0) },
                { "thrust", new GbayVehicleRecord("allin1.online-content", "catalog-only", "thrust", "Thrust", "DINKA", "motorcycles", 0, Storage, "mpbusiness2", 0, null, null, false, 1.0) },
                { "titan", new GbayVehicleRecord("allin1.online-content", "catalog-only", "titan", "Titan", "", "planes", 0, Storage, "base", 0, null, null, false, 1.0) },
                { "tornado5", new GbayVehicleRecord("allin1.online-content", "catalog-only", "tornado5", "Tornado Custom", "DECLASSE", "sportsclassics", 0, Storage, "mplowrider2", 0, null, null, false, 1.0) },
                { "tornado6", new GbayVehicleRecord("allin1.online-content", "catalog-only", "tornado6", "Tornado Rat Rod", "DECLASSE", "sportsclassics", 0, Storage, "mpbiker", 0, null, null, false, 1.0) },
                { "toro2", new GbayVehicleRecord("allin1.online-content", "catalog-only", "toro2", "Toro", "LAMPADA", "boats", 0, Storage, "mpapartment", 0, null, null, false, 1.0) },
                { "towtruck3", new GbayVehicleRecord("allin1.online-content", "catalog-only", "towtruck3", "Tow Truck", "", "service", 0, Storage, "mp2023_02", 0, null, null, false, 1.0) },
                { "tr2", new GbayVehicleRecord("allin1.online-content", "catalog-only", "tr2", "Trailer", "", "service", 0, Storage, "base", 0, null, null, false, 1.0) },
                { "tr3", new GbayVehicleRecord("allin1.online-content", "catalog-only", "tr3", "Trailer", "", "service", 0, Storage, "base", 0, null, null, false, 1.0) },
                { "tr4", new GbayVehicleRecord("allin1.online-content", "catalog-only", "tr4", "Trailer", "", "service", 0, Storage, "base", 0, null, null, false, 1.0) },
                { "trailerlarge", new GbayVehicleRecord("allin1.online-content", "catalog-only", "trailerlarge", "Mobile Operations Center", "", "service", 0, Storage, "mpgunrunning", 0, null, null, false, 1.0) },
                { "trailerlogs", new GbayVehicleRecord("allin1.online-content", "catalog-only", "trailerlogs", "Trailer", "", "service", 0, Storage, "base", 0, null, null, false, 1.0) },
                { "trailers", new GbayVehicleRecord("allin1.online-content", "catalog-only", "trailers", "Trailer", "", "service", 0, Storage, "base", 0, null, null, false, 1.0) },
                { "trailers2", new GbayVehicleRecord("allin1.online-content", "catalog-only", "trailers2", "Trailer", "", "service", 0, Storage, "base", 0, null, null, false, 1.0) },
                { "trailers3", new GbayVehicleRecord("allin1.online-content", "catalog-only", "trailers3", "Trailer", "", "service", 0, Storage, "base", 0, null, null, false, 1.0) },
                { "trailers4", new GbayVehicleRecord("allin1.online-content", "catalog-only", "trailers4", "Trailer", "", "service", 0, Storage, "mpgunrunning", 0, null, null, false, 1.0) },
                { "trailers5", new GbayVehicleRecord("allin1.online-content", "catalog-only", "trailers5", "Trailer", "", "service", 0, Storage, "mp2023_02", 0, null, null, false, 1.0) },
                { "trailersmall", new GbayVehicleRecord("allin1.online-content", "catalog-only", "trailersmall", "Trailer", "", "service", 0, Storage, "base", 0, null, null, false, 1.0) },
                { "trailersmall2", new GbayVehicleRecord("allin1.online-content", "catalog-only", "trailersmall2", "Anti-Aircraft Trailer", "VOMFEUER", "military", 0, Storage, "mpgunrunning", 0, null, null, false, 1.0) },
                { "trash2", new GbayVehicleRecord("allin1.online-content", "catalog-only", "trash2", "Trashmaster", "", "service", 0, Storage, "mpheist", 0, null, null, false, 1.0) },
                { "trflat", new GbayVehicleRecord("allin1.online-content", "catalog-only", "trflat", "Trailer", "", "service", 0, Storage, "base", 0, null, null, false, 1.0) },
                { "trflat2", new GbayVehicleRecord("allin1.online-content", "catalog-only", "trflat2", "TRAILER", "", "service", 0, Storage, "mp2026_01", 0, null, null, false, 1.0) },
                { "tropic2", new GbayVehicleRecord("allin1.online-content", "catalog-only", "tropic2", "Tropic", "SHITZU", "boats", 0, Storage, "mpapartment", 0, null, null, false, 1.0) },
                { "turismor", new GbayVehicleRecord("allin1.online-content", "catalog-only", "turismor", "Turismo R", "GROTTI", "super", 0, Storage, "mpbusiness", 0, null, null, false, 1.0) },
                { "tvtrailer", new GbayVehicleRecord("allin1.online-content", "catalog-only", "tvtrailer", "Trailer", "", "service", 0, Storage, "base", 0, null, null, false, 1.0) },
                { "tvtrailer2", new GbayVehicleRecord("allin1.online-content", "catalog-only", "tvtrailer2", "Trailer", "", "service", 0, Storage, "mp2023_02", 0, null, null, false, 1.0) },
                { "valkyrie2", new GbayVehicleRecord("allin1.online-content", "catalog-only", "valkyrie2", "Valkyrie MOD.0", "", "helicopters", 0, Storage, "mpapartment", 0, null, null, false, 1.0) },
                { "velum", new GbayVehicleRecord("allin1.online-content", "catalog-only", "velum", "Velum", "", "planes", 0, Storage, "base", 0, null, null, false, 1.0) },
                { "vestra", new GbayVehicleRecord("allin1.online-content", "catalog-only", "vestra", "Vestra", "BUCKING", "planes", 0, Storage, "mpbusiness", 0, null, null, false, 1.0) },
                { "veto", new GbayVehicleRecord("allin1.online-content", "catalog-only", "veto", "Veto Classic", "DINKA", "sports", 0, Storage, "mpheist4", 0, null, null, false, 1.0) },
                { "veto2", new GbayVehicleRecord("allin1.online-content", "catalog-only", "veto2", "Veto Modern", "DINKA", "sports", 0, Storage, "mpheist4", 0, null, null, false, 1.0) },
                { "virgo", new GbayVehicleRecord("allin1.online-content", "catalog-only", "virgo", "Virgo", "ALBANY", "muscle", 0, Storage, "mpluxe", 0, null, null, false, 1.0) },
                { "voodoo", new GbayVehicleRecord("allin1.online-content", "catalog-only", "voodoo", "Voodoo Custom", "DECLASSE", "muscle", 0, Storage, "mplowrider", 0, null, null, false, 1.0) },
                { "warrener", new GbayVehicleRecord("allin1.online-content", "catalog-only", "warrener", "Warrener", "VULCAR", "sedans", 0, Storage, "mphipster", 0, null, null, false, 1.0) },
                { "xls", new GbayVehicleRecord("allin1.online-content", "catalog-only", "xls", "XLS", "BENEFAC", "suvs", 0, Storage, "mpexecutive", 0, null, null, false, 1.0) },
                { "youga4", new GbayVehicleRecord("allin1.online-content", "catalog-only", "youga4", "Youga Custom", "VAPID", "vans", 0, Storage, "mpsecurity", 0, null, null, false, 1.0) },
                { "zentorno", new GbayVehicleRecord("allin1.online-content", "catalog-only", "zentorno", "Zentorno", "PEGASSI", "super", 0, Storage, "mpbusiness2", 0, null, null, false, 1.0) },
                { "zr380", new GbayVehicleRecord("allin1.online-content", "catalog-only", "zr380", "Apocalypse ZR380", "ANNIS", "sports", 0, Storage, "mpchristmas2018", 0, null, null, false, 1.0) },
                { "zr3802", new GbayVehicleRecord("allin1.online-content", "catalog-only", "zr3802", "Future Shock ZR380", "ANNIS", "sports", 0, Storage, "mpchristmas2018", 0, null, null, false, 1.0) },
                { "zr3803", new GbayVehicleRecord("allin1.online-content", "catalog-only", "zr3803", "Nightmare ZR380", "ANNIS", "sports", 0, Storage, "mpchristmas2018", 0, null, null, false, 1.0) },
            };
    }
}
