// VehicleList.cs - Auto-generated from data/vehicles.toml + prices_vehicles.toml
// 444 GTA Online DLC vehicles by class.
using System.Collections.Generic;

namespace ALLIN1
{
    internal static class VehicleList
    {
        internal static readonly string[] All = {
            "brioso",
            "brioso2",
            "brioso3",
            "weevil",
            "club",
            "kanjo",
            "asbo",
            "issi3",
            "kanjosj",
            "postlude",
            "previon",
            "windsor2",
            "windsor",
            "fr36",
            "eurosx32",
            "rhinehart",
            "deity",
            "cinquemila",
            "tailgater2",
            "warrener2",
            "glendale2",
            "stafford",
            "schafter3",
            "schafter4",
            "limo2",
            "schafter5",
            "schafter6",
            "cog552",
            "cog55",
            "cognoscenti2",
            "cognoscenti",
            "primo2",
            "asterope2",
            "impaler5",
            "vorschlaghammer",
            "chavosv6",
            "hardy",
            "minimus",
            "sentinel6",
            "issi8",
            "granger2",
            "iwagen",
            "baller7",
            "astron",
            "jubilee",
            "seminole2",
            "landstalker2",
            "rebla",
            "novak",
            "toros",
            "stretch",
            "contender",
            "xls2",
            "baller3",
            "baller4",
            "baller5",
            "baller6",
            "vivanite",
            "aleutian",
            "cavalcade3",
            "baller8",
            "dorado",
            "castigator",
            "astron2",
            "everon3",
            "woodlander",
            "tahoma",
            "tulip2",
            "weevil2",
            "vigero2",
            "ruiner4",
            "buffalo4",
            "dominator7",
            "dominator8",
            "gauntlet5",
            "manana2",
            "dukes3",
            "yosemite2",
            "peyote2",
            "gauntlet4",
            "gauntlet3",
            "vamos",
            "deviant",
            "tulip",
            "clique",
            "imperator",
            "impaler",
            "dominator3",
            "ellie",
            "hustler",
            "hermes",
            "yosemite",
            "tampa3",
            "ruiner2",
            "sabregt2",
            "virgo2",
            "virgo3",
            "faction3",
            "tampa",
            "nightshade",
            "moonbeam2",
            "moonbeam",
            "faction2",
            "faction",
            "chino2",
            "buccaneer2",
            "coquette3",
            "chino",
            "vigero",
            "slamvan2",
            "clique2",
            "buffalo5",
            "vigero3",
            "dominator9",
            "impaler6",
            "dominator10",
            "arbitergt",
            "tampa4",
            "everon2",
            "panthere",
            "r300",
            "sentinel4",
            "tenf2",
            "tenf",
            "sm722",
            "omnisegt",
            "corsita",
            "comet7",
            "cypher",
            "sultan3",
            "growler",
            "vectre",
            "comet6",
            "remus",
            "jester4",
            "rt3000",
            "zr350",
            "euros",
            "futo2",
            "italirsx",
            "penumbra2",
            "coquette4",
            "sugoi",
            "vstr",
            "sultan2",
            "imorgon",
            "komoda",
            "jugular",
            "zion3",
            "locust",
            "nebula",
            "neo",
            "issi7",
            "drafter",
            "paragon",
            "paragon2",
            "schlagen",
            "italigto",
            "swinger",
            "jester3",
            "michelli",
            "flashgt",
            "gb200",
            "hotring",
            "comet5",
            "z190",
            "neon",
            "revolter",
            "gt500",
            "viseris",
            "savestra",
            "streiter",
            "sentinel3",
            "raiden",
            "pariah",
            "comet4",
            "rapidgt3",
            "retinue",
            "ardent",
            "torero",
            "cheetah2",
            "turismo2",
            "infernus2",
            "ruston",
            "specter2",
            "specter",
            "comet3",
            "elegy",
            "tampa2",
            "lynx",
            "tropos",
            "omnis",
            "seven70",
            "bestiagts",
            "mamba",
            "verlierer2",
            "schafter3",
            "schafter4",
            "feltzer3",
            "casco",
            "kuruma",
            "kuruma2",
            "stingertt",
            "gauntlet6",
            "coureur",
            "coquette5",
            "envisage",
            "niobe",
            "paragon3",
            "banshee3",
            "jester5",
            "coquette6",
            "s95",
            "cheetah3",
            "rapidgt4",
            "sentinel5",
            "astrale",
            "gt750",
            "itali2",
            "virtue",
            "entity3",
            "lm87",
            "torero2",
            "zeno",
            "ignus",
            "champion",
            "tigon",
            "furia",
            "zorrusso",
            "krieger",
            "emerus",
            "s80",
            "thrax",
            "deveste",
            "tyrant",
            "tezeract",
            "taipan",
            "entity2",
            "autarch",
            "sc1",
            "cyclone",
            "visione",
            "xa21",
            "vagner",
            "gp1",
            "italigtb",
            "italigtb2",
            "nero",
            "nero2",
            "tempesta",
            "penetrator",
            "tyrus",
            "le7b",
            "sheava",
            "pfister811",
            "prototipo",
            "reaper",
            "fmj",
            "sultanrs",
            "banshee2",
            "t20",
            "osiris",
            "turismo3",
            "pipistrello",
            "cyclone2",
            "suzume",
            "fmj2",
            "luiva",
            "xtreme",
            "boor",
            "draugur",
            "patriot3",
            "verus",
            "yosemite3",
            "outlaw",
            "zhaba",
            "everon",
            "vagrant",
            "hellion",
            "caracara2",
            "brutus",
            "monster3",
            "bruiser",
            "freecrawler",
            "menacer",
            "caracara",
            "kamacho",
            "riata",
            "nightshark",
            "technical3",
            "dune3",
            "blazer5",
            "blazer4",
            "rallytruck",
            "trophytruck",
            "trophytruck2",
            "brawler",
            "technical",
            "insurgent",
            "guardian",
            "l35",
            "ratel",
            "monstrociti",
            "terminus",
            "yosemite1500",
            "firebolt",
            "uranus",
            "l352",
            "powersurge",
            "manchez3",
            "reever",
            "shinobi",
            "manchez2",
            "stryder",
            "fcr2",
            "fcr",
            "diablous",
            "diablous2",
            "esskey",
            "vortex",
            "daemon2",
            "zombiea",
            "zombieb",
            "wolfsbane",
            "nightblade",
            "manchez",
            "hakuchou2",
            "faggio",
            "faggio3",
            "defiler",
            "chimera",
            "avarus",
            "cliffhanger",
            "gargoyle",
            "bf400",
            "vindicator",
            "lectro",
            "enduro",
            "longfin",
            "toro",
            "avisa",
            "dinghy5",
            "patrolboat",
            "tug",
            "conada",
            "havok",
            "volatus",
            "supervolito",
            "supervolito2",
            "swift2",
            "annihilator2",
            "akula",
            "hunter",
            "valkyrie",
            "savage",
            "microlight",
            "nimbus",
            "luxor2",
            "velum2",
            "alkonost",
            "strikeforce",
            "avenger",
            "volatol",
            "nokota",
            "seabreeze",
            "pyro",
            "mogul",
            "howard",
            "bombushka",
            "molotok",
            "tula",
            "rogue",
            "starling",
            "alphaz1",
            "hydra",
            "vetir",
            "scarab",
            "terbyte",
            "thruster",
            "khanjali",
            "chernobog",
            "barrage",
            "halftrack",
            "apc",
            "oppressor",
            "oppressor2",
            "squaddie",
            "winky",
            "insurgent3",
            "raiju",
            "streamer216",
            "conada2",
            "pounder2",
            "mule4",
            "phantom3",
            "hauler2",
            "phantom2",
            "mule3",
            "boxville4",
            "flatbed2",
            "stockade4",
            "keitora",
            "openwheel1",
            "openwheel2",
            "formula",
            "formula2",
            "raptor",
            "journey2",
            "surfer3",
            "youga3",
            "speedo4",
            "youga2",
            "rumpo3",
            "minivan2",
            "boxville6",
            "riot2",
            "polgauntlet",
            "police5",
            "polbuffalo",
            "polbuffalo6",
            "policet3",
            "policeb2",
            "polcoquette4",
            "polcaracara",
            "polfaction2",
            "polterminus",
            "inductor",
            "inductor2",
            "pbus2",
            "benson2",
            "slamtruck",
            "wastelander",
            "towtruck4",
            "pizzaboy",
            "scramjet",
            "vigilante",
            "voltic2",
            "toreador",
            "jb7002",
            "deluxo",
            "stromberg",
            "rrocket",
            "shotaro",
            "dune5",
        };

        internal static readonly string[] Boats = {
            "longfin",
            "toro",
            "avisa",
            "dinghy5",
            "patrolboat",
            "tug",
        };

        internal static readonly string[] Compacts = {
            "brioso",
            "brioso2",
            "brioso3",
            "weevil",
            "club",
            "kanjo",
            "asbo",
            "issi3",
        };

        internal static readonly string[] Coupes = {
            "kanjosj",
            "postlude",
            "previon",
            "windsor2",
            "windsor",
            "fr36",
            "eurosx32",
        };

        internal static readonly string[] Cycles = {
            "inductor",
            "inductor2",
        };

        internal static readonly string[] Emergency = {
            "riot2",
            "polgauntlet",
            "police5",
            "polbuffalo",
            "polbuffalo6",
            "policet3",
            "policeb2",
            "polcoquette4",
            "polcaracara",
            "polfaction2",
            "polterminus",
        };

        internal static readonly string[] Helicopters = {
            "conada",
            "havok",
            "volatus",
            "supervolito",
            "supervolito2",
            "swift2",
            "annihilator2",
            "akula",
            "hunter",
            "valkyrie",
            "savage",
        };

        internal static readonly string[] Industrial = {
            "pounder2",
            "mule4",
            "phantom3",
            "hauler2",
            "phantom2",
            "mule3",
            "boxville4",
            "flatbed2",
            "stockade4",
            "keitora",
        };

        internal static readonly string[] Military = {
            "vetir",
            "scarab",
            "terbyte",
            "thruster",
            "khanjali",
            "chernobog",
            "barrage",
            "halftrack",
            "apc",
            "oppressor",
            "oppressor2",
            "squaddie",
            "winky",
            "insurgent3",
            "raiju",
            "streamer216",
            "conada2",
        };

        internal static readonly string[] Motorcycles = {
            "powersurge",
            "manchez3",
            "reever",
            "shinobi",
            "manchez2",
            "stryder",
            "fcr2",
            "fcr",
            "diablous",
            "diablous2",
            "esskey",
            "vortex",
            "daemon2",
            "zombiea",
            "zombieb",
            "wolfsbane",
            "nightblade",
            "manchez",
            "hakuchou2",
            "faggio",
            "faggio3",
            "defiler",
            "chimera",
            "avarus",
            "cliffhanger",
            "gargoyle",
            "bf400",
            "vindicator",
            "lectro",
            "enduro",
        };

        internal static readonly string[] Muscle = {
            "tahoma",
            "tulip2",
            "weevil2",
            "vigero2",
            "ruiner4",
            "buffalo4",
            "dominator7",
            "dominator8",
            "gauntlet5",
            "manana2",
            "dukes3",
            "yosemite2",
            "peyote2",
            "gauntlet4",
            "gauntlet3",
            "vamos",
            "deviant",
            "tulip",
            "clique",
            "imperator",
            "impaler",
            "dominator3",
            "ellie",
            "hustler",
            "hermes",
            "yosemite",
            "tampa3",
            "ruiner2",
            "sabregt2",
            "virgo2",
            "virgo3",
            "faction3",
            "tampa",
            "nightshade",
            "moonbeam2",
            "moonbeam",
            "faction2",
            "faction",
            "chino2",
            "buccaneer2",
            "coquette3",
            "chino",
            "vigero",
            "slamvan2",
            "clique2",
            "buffalo5",
            "vigero3",
            "dominator9",
            "impaler6",
            "dominator10",
            "arbitergt",
            "tampa4",
        };

        internal static readonly string[] Offroad = {
            "boor",
            "draugur",
            "patriot3",
            "verus",
            "yosemite3",
            "outlaw",
            "zhaba",
            "everon",
            "vagrant",
            "hellion",
            "caracara2",
            "brutus",
            "monster3",
            "bruiser",
            "freecrawler",
            "menacer",
            "caracara",
            "kamacho",
            "riata",
            "nightshark",
            "technical3",
            "dune3",
            "blazer5",
            "blazer4",
            "rallytruck",
            "trophytruck",
            "trophytruck2",
            "brawler",
            "technical",
            "insurgent",
            "guardian",
            "l35",
            "ratel",
            "monstrociti",
            "terminus",
            "yosemite1500",
            "firebolt",
            "uranus",
            "l352",
        };

        internal static readonly string[] Openwheel = {
            "openwheel1",
            "openwheel2",
            "formula",
            "formula2",
            "raptor",
        };

        internal static readonly string[] Planes = {
            "microlight",
            "nimbus",
            "luxor2",
            "velum2",
            "alkonost",
            "strikeforce",
            "avenger",
            "volatol",
            "nokota",
            "seabreeze",
            "pyro",
            "mogul",
            "howard",
            "bombushka",
            "molotok",
            "tula",
            "rogue",
            "starling",
            "alphaz1",
            "hydra",
        };

        internal static readonly string[] Sedans = {
            "rhinehart",
            "deity",
            "cinquemila",
            "tailgater2",
            "warrener2",
            "glendale2",
            "stafford",
            "schafter3",
            "schafter4",
            "limo2",
            "schafter5",
            "schafter6",
            "cog552",
            "cog55",
            "cognoscenti2",
            "cognoscenti",
            "primo2",
            "asterope2",
            "impaler5",
            "vorschlaghammer",
            "chavosv6",
            "hardy",
            "minimus",
            "sentinel6",
        };

        internal static readonly string[] Service = {
            "pbus2",
            "benson2",
            "slamtruck",
            "wastelander",
            "towtruck4",
            "pizzaboy",
        };

        internal static readonly string[] Special = {
            "scramjet",
            "vigilante",
            "voltic2",
            "toreador",
            "jb7002",
            "deluxo",
            "stromberg",
            "rrocket",
            "shotaro",
            "dune5",
        };

        internal static readonly string[] Sportsclassics = {
            "everon2",
            "panthere",
            "r300",
            "sentinel4",
            "tenf2",
            "tenf",
            "sm722",
            "omnisegt",
            "corsita",
            "comet7",
            "cypher",
            "sultan3",
            "growler",
            "vectre",
            "comet6",
            "remus",
            "jester4",
            "rt3000",
            "zr350",
            "euros",
            "futo2",
            "italirsx",
            "penumbra2",
            "coquette4",
            "sugoi",
            "vstr",
            "sultan2",
            "imorgon",
            "komoda",
            "jugular",
            "zion3",
            "locust",
            "nebula",
            "neo",
            "issi7",
            "drafter",
            "paragon",
            "paragon2",
            "schlagen",
            "italigto",
            "swinger",
            "jester3",
            "michelli",
            "flashgt",
            "gb200",
            "hotring",
            "comet5",
            "z190",
            "neon",
            "revolter",
            "gt500",
            "viseris",
            "savestra",
            "streiter",
            "sentinel3",
            "raiden",
            "pariah",
            "comet4",
            "rapidgt3",
            "retinue",
            "ardent",
            "torero",
            "cheetah2",
            "turismo2",
            "infernus2",
            "ruston",
            "specter2",
            "specter",
            "comet3",
            "elegy",
            "tampa2",
            "lynx",
            "tropos",
            "omnis",
            "seven70",
            "bestiagts",
            "mamba",
            "verlierer2",
            "schafter3",
            "schafter4",
            "feltzer3",
            "casco",
            "kuruma",
            "kuruma2",
            "stingertt",
            "gauntlet6",
            "coureur",
            "coquette5",
            "envisage",
            "niobe",
            "paragon3",
            "banshee3",
            "jester5",
            "coquette6",
            "s95",
            "cheetah3",
            "rapidgt4",
            "sentinel5",
            "astrale",
            "gt750",
            "itali2",
        };

        internal static readonly string[] Super = {
            "virtue",
            "entity3",
            "lm87",
            "torero2",
            "zeno",
            "ignus",
            "champion",
            "tigon",
            "furia",
            "zorrusso",
            "krieger",
            "emerus",
            "s80",
            "thrax",
            "deveste",
            "tyrant",
            "tezeract",
            "taipan",
            "entity2",
            "autarch",
            "sc1",
            "cyclone",
            "visione",
            "xa21",
            "vagner",
            "gp1",
            "italigtb",
            "italigtb2",
            "nero",
            "nero2",
            "tempesta",
            "penetrator",
            "tyrus",
            "le7b",
            "sheava",
            "pfister811",
            "prototipo",
            "reaper",
            "fmj",
            "sultanrs",
            "banshee2",
            "t20",
            "osiris",
            "turismo3",
            "pipistrello",
            "cyclone2",
            "suzume",
            "fmj2",
            "luiva",
            "xtreme",
        };

        internal static readonly string[] Suvs = {
            "issi8",
            "granger2",
            "iwagen",
            "baller7",
            "astron",
            "jubilee",
            "seminole2",
            "landstalker2",
            "rebla",
            "novak",
            "toros",
            "stretch",
            "contender",
            "xls2",
            "baller3",
            "baller4",
            "baller5",
            "baller6",
            "vivanite",
            "aleutian",
            "cavalcade3",
            "baller8",
            "dorado",
            "castigator",
            "astron2",
            "everon3",
            "woodlander",
        };

        internal static readonly string[] Vans = {
            "journey2",
            "surfer3",
            "youga3",
            "speedo4",
            "youga2",
            "rumpo3",
            "minivan2",
            "boxville6",
        };

        internal static readonly string[] Weaponized = {
            "akula",
            "alkonost",
            "annihilator2",
            "apc",
            "avenger",
            "barrage",
            "blazer5",
            "bombushka",
            "bruiser",
            "brutus",
            "buffalo4",
            "champion",
            "chernobog",
            "conada2",
            "deluxo",
            "dinghy5",
            "halftrack",
            "hunter",
            "imperator",
            "insurgent",
            "insurgent3",
            "khanjali",
            "menacer",
            "mogul",
            "molotok",
            "mule4",
            "nightshark",
            "nokota",
            "oppressor",
            "oppressor2",
            "patriot3",
            "pounder2",
            "pyro",
            "raiju",
            "rogue",
            "ruiner2",
            "savage",
            "scarab",
            "scramjet",
            "seabreeze",
            "speedo4",
            "starling",
            "streamer216",
            "strikeforce",
            "stromberg",
            "tampa3",
            "technical",
            "technical3",
            "terbyte",
            "thruster",
            "tula",
            "valkyrie",
            "vetir",
            "vigilante",
            "volatol",
        };

        internal static readonly Dictionary<string, string> DisplayNames = new Dictionary<string, string>
        {
            { "brioso", "Grotti Brioso R/A" },
            { "brioso2", "Grotti Brioso 300" },
            { "brioso3", "Grotti Brioso 300 Widebody" },
            { "weevil", "BF Weevil" },
            { "club", "BF Club" },
            { "kanjo", "Dinka Blista Kanjo" },
            { "asbo", "Maxwell Asbo" },
            { "issi3", "Weeny Issi Classic" },
            { "kanjosj", "Dinka Kanjo SJ" },
            { "postlude", "Dinka Postlude" },
            { "previon", "Karin Previon" },
            { "windsor2", "Enus Windsor Drop" },
            { "windsor", "Enus Windsor" },
            { "fr36", "Benefactor FR36" },
            { "eurosx32", "Annis Euros X32" },
            { "rhinehart", "Ubermacht Rhinehart" },
            { "deity", "Enus Deity" },
            { "cinquemila", "Lampadati Cinquemila" },
            { "tailgater2", "Obey Tailgater S" },
            { "warrener2", "Vulcar Warrener HKR" },
            { "glendale2", "Benefactor Glendale Custom" },
            { "stafford", "Enus Stafford" },
            { "schafter3", "Benefactor Schafter V12" },
            { "schafter4", "Benefactor Schafter LWB" },
            { "limo2", "Benefactor Turreted Limo" },
            { "schafter5", "Benefactor Schafter V12 (Armored)" },
            { "schafter6", "Benefactor Schafter LWB (Armored)" },
            { "cog552", "Enus Cognoscenti 55 (Armored)" },
            { "cog55", "Enus Cognoscenti 55" },
            { "cognoscenti2", "Enus Cognoscenti (Armored)" },
            { "cognoscenti", "Enus Cognoscenti" },
            { "primo2", "Albany Primo Custom" },
            { "asterope2", "Karin Asterope GZ" },
            { "impaler5", "Declasse Impaler LX" },
            { "vorschlaghammer", "Benefactor Vorschlaghammer" },
            { "chavosv6", "Dinka Chavos V6" },
            { "hardy", "Annis Hardy" },
            { "minimus", "Annis Minimus" },
            { "sentinel6", "Ubermacht Sentinel Classic II" },
            { "issi8", "Weeny Issi Rally" },
            { "granger2", "Declasse Granger 3600LX" },
            { "iwagen", "Obey I-Wagen" },
            { "baller7", "Gallivanter Baller ST" },
            { "astron", "Pfister Astron" },
            { "jubilee", "Enus Jubilee" },
            { "seminole2", "Canis Seminole Frontier" },
            { "landstalker2", "Dundreary Landstalker XL" },
            { "rebla", "Ubermacht Rebla GTS" },
            { "novak", "Lampadati Novak" },
            { "toros", "Pegassi Toros" },
            { "stretch", "Dundreary Stretch" },
            { "contender", "Vapid Contender" },
            { "xls2", "Benefactor XLS (Armored)" },
            { "baller3", "Gallivanter Baller LE" },
            { "baller4", "Gallivanter Baller LE LWB" },
            { "baller5", "Gallivanter Baller LE (Armored)" },
            { "baller6", "Gallivanter Baller LE LWB (Armored)" },
            { "vivanite", "Declasse Vivanite" },
            { "aleutian", "Albany Aleutian" },
            { "cavalcade3", "Albany Cavalcade XL" },
            { "baller8", "Gallivanter Baller ST-D" },
            { "dorado", "Bravado Dorado" },
            { "castigator", "Declasse Castigator" },
            { "astron2", "Pfister Astron Custom" },
            { "everon3", "Karin Everon RS" },
            { "woodlander", "Vapid Woodlander" },
            { "tahoma", "Declasse Tahoma Coupe" },
            { "tulip2", "Declasse Tulip M-100" },
            { "weevil2", "BF Weevil Custom" },
            { "vigero2", "Declasse Vigero ZX" },
            { "ruiner4", "Imponte Ruiner ZZ-8" },
            { "buffalo4", "Bravado Buffalo STX" },
            { "dominator7", "Vapid Dominator ASP" },
            { "dominator8", "Vapid Dominator GTT" },
            { "gauntlet5", "Bravado Gauntlet Classic Custom" },
            { "manana2", "Albany Manana Custom" },
            { "dukes3", "Imponte Beater Dukes" },
            { "yosemite2", "Declasse Drift Yosemite" },
            { "peyote2", "Vapid Peyote Gasser" },
            { "gauntlet4", "Bravado Gauntlet Hellfire" },
            { "gauntlet3", "Bravado Gauntlet Classic" },
            { "vamos", "Declasse Vamos" },
            { "deviant", "Schyster Deviant" },
            { "tulip", "Declasse Tulip" },
            { "clique", "Vapid Clique" },
            { "imperator", "Vapid Imperator" },
            { "impaler", "Declasse Impaler" },
            { "dominator3", "Vapid Dominator GTX" },
            { "ellie", "Vapid Ellie" },
            { "hustler", "Vapid Hustler" },
            { "hermes", "Albany Hermes" },
            { "yosemite", "Declasse Yosemite" },
            { "tampa3", "Declasse Weaponized Tampa" },
            { "ruiner2", "Imponte Ruiner 2000" },
            { "sabregt2", "Declasse Sabre Turbo Custom" },
            { "virgo2", "Dundreary Virgo Classic Custom" },
            { "virgo3", "Dundreary Virgo Classic" },
            { "faction3", "Willard Faction Custom Donk" },
            { "tampa", "Declasse Tampa" },
            { "nightshade", "Imponte Nightshade" },
            { "moonbeam2", "Declasse Moonbeam Custom" },
            { "moonbeam", "Declasse Moonbeam" },
            { "faction2", "Willard Faction Custom" },
            { "faction", "Willard Faction" },
            { "chino2", "Vapid Chino Custom" },
            { "buccaneer2", "Albany Buccaneer Custom" },
            { "coquette3", "Invetero Coquette BlackFin" },
            { "chino", "Vapid Chino" },
            { "vigero", "Declasse Vigero" },
            { "slamvan2", "Vapid Slamvan Custom" },
            { "clique2", "Vapid Clique Wagon" },
            { "buffalo5", "Bravado Buffalo EVX" },
            { "vigero3", "Declasse Vigero ZX Convertible" },
            { "dominator9", "Vapid Dominator GT" },
            { "impaler6", "Declasse Impaler LX" },
            { "dominator10", "Vapid Dominator FX" },
            { "arbitergt", "Vapid Arbiter GT" },
            { "tampa4", "Declasse Drift Tampa" },
            { "everon2", "Karin Hotring Everon" },
            { "panthere", "Toundra Panthere" },
            { "r300", "Annis 300R" },
            { "sentinel4", "Ubermacht Sentinel Classic Widebody" },
            { "tenf2", "Obey 10F Widebody" },
            { "tenf", "Obey 10F" },
            { "sm722", "Benefactor SM722" },
            { "omnisegt", "Obey Omnis e-GT" },
            { "corsita", "Lampadati Corsita" },
            { "comet7", "Pfister Comet S2 Cabrio" },
            { "cypher", "Ubermacht Cypher" },
            { "sultan3", "Karin Sultan RS Classic" },
            { "growler", "Pfister Growler" },
            { "vectre", "Emperor Vectre" },
            { "comet6", "Pfister Comet S2" },
            { "remus", "Annis Remus" },
            { "jester4", "Dinka Jester RR" },
            { "rt3000", "Dinka RT3000" },
            { "zr350", "Annis ZR350" },
            { "euros", "Annis Euros" },
            { "futo2", "Karin Futo GTX" },
            { "italirsx", "Ocelot Itali RSX" },
            { "penumbra2", "Maibatsu Penumbra FF" },
            { "coquette4", "Invetero Coquette D10" },
            { "sugoi", "Dinka Sugoi" },
            { "vstr", "Albany V-STR" },
            { "sultan2", "Karin Sultan Classic" },
            { "imorgon", "Overflod Imorgon" },
            { "komoda", "Lampadati Komoda" },
            { "jugular", "Ocelot Jugular" },
            { "zion3", "Ubermacht Zion Classic" },
            { "locust", "Ocelot Locust" },
            { "nebula", "Vulcar Nebula Turbo" },
            { "neo", "Vysser Neo" },
            { "issi7", "Weeny Issi Sport" },
            { "drafter", "Obey 8F Drafter" },
            { "paragon", "Enus Paragon R" },
            { "paragon2", "Enus Paragon R (Armored)" },
            { "schlagen", "Benefactor Schlagen GT" },
            { "italigto", "Grotti Itali GTO" },
            { "swinger", "Ocelot Swinger" },
            { "jester3", "Dinka Jester Classic" },
            { "michelli", "Lampadati Michelli GT" },
            { "flashgt", "Vapid Flash GT" },
            { "gb200", "Vapid GB200" },
            { "hotring", "Declasse Hotring Sabre" },
            { "comet5", "Pfister Comet SR" },
            { "z190", "Karin 190z" },
            { "neon", "Pfister Neon" },
            { "revolter", "Ubermacht Revolter" },
            { "gt500", "Grotti GT500" },
            { "viseris", "Lampadati Viseris" },
            { "savestra", "Annis Savestra" },
            { "streiter", "Benefactor Streiter" },
            { "sentinel3", "Ubermacht Sentinel Classic" },
            { "raiden", "Coil Raiden" },
            { "pariah", "Ocelot Pariah" },
            { "comet4", "Pfister Comet Safari" },
            { "rapidgt3", "Dewbauchee Rapid GT Classic" },
            { "retinue", "Vapid Retinue" },
            { "ardent", "Ocelot Ardent" },
            { "torero", "Pegassi Torero" },
            { "cheetah2", "Grotti Cheetah Classic" },
            { "turismo2", "Grotti Turismo Classic" },
            { "infernus2", "Pegassi Infernus Classic" },
            { "ruston", "Hijak Ruston" },
            { "specter2", "Dewbauchee Specter Custom" },
            { "specter", "Dewbauchee Specter" },
            { "comet3", "Pfister Comet Retro Custom" },
            { "elegy", "Annis Elegy Retro Custom" },
            { "tampa2", "Declasse Drift Tampa" },
            { "lynx", "Ocelot Lynx" },
            { "tropos", "Lampadati Tropos Rallye" },
            { "omnis", "Obey Omnis" },
            { "seven70", "Dewbauchee Seven-70" },
            { "bestiagts", "Grotti Bestia GTS" },
            { "mamba", "Declasse Mamba" },
            { "verlierer2", "Benefactor Feltzer" },
            { "feltzer3", "Benefactor Stirling GT" },
            { "casco", "Lampadati Casco" },
            { "kuruma", "Karin Kuruma" },
            { "kuruma2", "Karin Kuruma (Armored)" },
            { "stingertt", "Grotti Stinger TT" },
            { "gauntlet6", "Bravado Hotring Hellfire" },
            { "coureur", "Penaud La Coureuse" },
            { "coquette5", "Invetero Coquette D1" },
            { "envisage", "Bollokan Envisage" },
            { "niobe", "Ubermacht Niobe" },
            { "paragon3", "Enus Paragon S" },
            { "banshee3", "Bravado Banshee GTS" },
            { "jester5", "Dinka LSCM Jester RR" },
            { "coquette6", "Invetero Coquette D5" },
            { "s95", "Karin S95" },
            { "cheetah3", "Grotti LSCM Cheetah Classic" },
            { "rapidgt4", "Dewbauchee Rapid GT X" },
            { "sentinel5", "Ubermacht Sentinel GTS" },
            { "astrale", "Pfister Astrale" },
            { "gt750", "Grotti GT750" },
            { "itali2", "Grotti Itali Classic" },
            { "virtue", "Ocelot Virtue" },
            { "entity3", "Overflod Entity MT" },
            { "lm87", "Benefactor LM87" },
            { "torero2", "Pegassi Torero XO" },
            { "zeno", "Overflod Zeno" },
            { "ignus", "Pegassi Ignus" },
            { "champion", "Dewbauchee Champion" },
            { "tigon", "Lampadati Tigon" },
            { "furia", "Grotti Furia" },
            { "zorrusso", "Pegassi Zorrusso" },
            { "krieger", "Benefactor Krieger" },
            { "emerus", "Progen Emerus" },
            { "s80", "Annis S80RR" },
            { "thrax", "Truffade Thrax" },
            { "deveste", "Principe Deveste Eight" },
            { "tyrant", "Overflod Tyrant" },
            { "tezeract", "Pegassi Tezeract" },
            { "taipan", "Cheval Taipan" },
            { "entity2", "Overflod Entity XXR" },
            { "autarch", "Overflod Autarch" },
            { "sc1", "Ubermacht SC1" },
            { "cyclone", "Coil Cyclone" },
            { "visione", "Grotti Visione" },
            { "xa21", "Ocelot XA-21" },
            { "vagner", "Dewbauchee Vagner" },
            { "gp1", "Progen GP1" },
            { "italigtb", "Progen Itali GTB" },
            { "italigtb2", "Progen Itali GTB Custom" },
            { "nero", "Truffade Nero" },
            { "nero2", "Truffade Nero Custom" },
            { "tempesta", "Pegassi Tempesta" },
            { "penetrator", "Ocelot Penetrator" },
            { "tyrus", "Progen Tyrus" },
            { "le7b", "Annis RE-7B" },
            { "sheava", "Emperor ETR1" },
            { "pfister811", "Pfister 811" },
            { "prototipo", "Grotti X80 Proto" },
            { "reaper", "Pegassi Reaper" },
            { "fmj", "Vapid FMJ" },
            { "sultanrs", "Karin Sultan RS" },
            { "banshee2", "Bravado Banshee 900R" },
            { "t20", "Progen T20" },
            { "osiris", "Pegassi Osiris" },
            { "turismo3", "Grotti Turismo Omaggio" },
            { "pipistrello", "Grotti Pipistrello" },
            { "cyclone2", "Coil Cyclone II" },
            { "suzume", "Overflod Suzume" },
            { "fmj2", "Vapid FMJ Mk V" },
            { "luiva", "Progen Luiva" },
            { "xtreme", "Pfister X-treme" },
            { "boor", "Karin Boor" },
            { "draugur", "Declasse Draugur" },
            { "patriot3", "Mammoth Patriot Mil-Spec" },
            { "verus", "Dinka Verus" },
            { "yosemite3", "Declasse Yosemite Rancher" },
            { "outlaw", "Nagasaki Outlaw" },
            { "zhaba", "RUNE Zhaba" },
            { "everon", "Karin Everon" },
            { "vagrant", "Maxwell Vagrant" },
            { "hellion", "Annis Hellion" },
            { "caracara2", "Vapid Caracara 4x4" },
            { "brutus", "Declasse Brutus" },
            { "monster3", "Declasse Apocalypse Sasquatch" },
            { "bruiser", "Benefactor Bruiser" },
            { "freecrawler", "Canis Freecrawler" },
            { "menacer", "HVY Menacer" },
            { "caracara", "Vapid Caracara" },
            { "kamacho", "Canis Kamacho" },
            { "riata", "Vapid Riata" },
            { "nightshark", "HVY Nightshark" },
            { "technical3", "Karin Technical Custom" },
            { "dune3", "BF Dune FAV" },
            { "blazer5", "Nagasaki Street Blazer" },
            { "blazer4", "Nagasaki Hot Rod Blazer" },
            { "rallytruck", "Vapid Rally Truck" },
            { "trophytruck", "Vapid Trophy Truck" },
            { "trophytruck2", "Vapid Desert Raid" },
            { "brawler", "Coil Brawler" },
            { "technical", "Karin Technical" },
            { "insurgent", "HVY Insurgent" },
            { "guardian", "Vapid Guardian" },
            { "l35", "Declasse Walton L35" },
            { "ratel", "Vapid Ratel" },
            { "monstrociti", "Maibatsu MonstroCiti" },
            { "terminus", "Canis Terminus" },
            { "yosemite1500", "Declasse Yosemite 1500" },
            { "firebolt", "Vapid Firebolt ASP" },
            { "uranus", "Vapid Uranus LozSpeed" },
            { "l352", "Declasse Drift Walton L35" },
            { "powersurge", "Western Powersurge" },
            { "manchez3", "Maibatsu Manchez Scout C" },
            { "reever", "Western Reever" },
            { "shinobi", "Nagasaki Shinobi" },
            { "manchez2", "Maibatsu Manchez Scout" },
            { "stryder", "Nagasaki Stryder" },
            { "fcr2", "Pegassi FCR 1000 Custom" },
            { "fcr", "Pegassi FCR 1000" },
            { "diablous", "Principe Diabolus" },
            { "diablous2", "Principe Diabolus Custom" },
            { "esskey", "Pegassi Esskey" },
            { "vortex", "Pegassi Vortex" },
            { "daemon2", "Western Daemon Custom" },
            { "zombiea", "Western Zombie Chopper" },
            { "zombieb", "Western Zombie Bobber" },
            { "wolfsbane", "Western Wolfsbane" },
            { "nightblade", "Western Nightblade" },
            { "manchez", "Maibatsu Manchez" },
            { "hakuchou2", "Shitzu Hakuchou Drag" },
            { "faggio", "Principe Faggio Mod" },
            { "faggio3", "Principe Faggio Sport" },
            { "defiler", "Shitzu Defiler" },
            { "chimera", "Nagasaki Chimera" },
            { "avarus", "LCC Avarus" },
            { "cliffhanger", "Western Cliffhanger" },
            { "gargoyle", "Western Gargoyle" },
            { "bf400", "Nagasaki BF400" },
            { "vindicator", "Dinka Vindicator" },
            { "lectro", "Principe Lectro" },
            { "enduro", "Dinka Enduro" },
            { "longfin", "Shitzu Longfin" },
            { "toro", "Lampadati Toro" },
            { "avisa", "Kraken Avisa" },
            { "dinghy5", "Nagasaki Weaponized Dinghy" },
            { "patrolboat", "Kurtz 31 Patrol Boat" },
            { "tug", "Buckingham Tug" },
            { "conada", "Buckingham Conada" },
            { "havok", "Nagasaki Havok" },
            { "volatus", "Buckingham Volatus" },
            { "supervolito", "Buckingham SuperVolito" },
            { "supervolito2", "Buckingham SuperVolito Carbon" },
            { "swift2", "Buckingham Swift Deluxe" },
            { "annihilator2", "Western Annihilator Stealth" },
            { "akula", "Akula" },
            { "hunter", "FH-1 Hunter" },
            { "valkyrie", "Buckingham Valkyrie" },
            { "savage", "Savage" },
            { "microlight", "Nagasaki Ultralight" },
            { "nimbus", "Buckingham Nimbus" },
            { "luxor2", "Buckingham Luxor Deluxe" },
            { "velum2", "Buckingham Velum 5-Seater" },
            { "alkonost", "RO-86 Alkonost" },
            { "strikeforce", "B-11 Strikeforce" },
            { "avenger", "Mammoth Avenger" },
            { "volatol", "Volatol" },
            { "nokota", "P-45 Nokota" },
            { "seabreeze", "Western Seabreeze" },
            { "pyro", "Buckingham Pyro" },
            { "mogul", "Mammoth Mogul" },
            { "howard", "Buckingham Howard NX-25" },
            { "bombushka", "RM-10 Bombushka" },
            { "molotok", "V-65 Molotok" },
            { "tula", "Mammoth Tula" },
            { "rogue", "Western Rogue" },
            { "starling", "LF-22 Starling" },
            { "alphaz1", "Buckingham Alpha-Z1" },
            { "hydra", "Mammoth Hydra" },
            { "vetir", "Vetir" },
            { "scarab", "HVY Scarab" },
            { "terbyte", "Benefactor Terrorbyte" },
            { "thruster", "Mammoth Thruster" },
            { "khanjali", "TM-02 Khanjali" },
            { "chernobog", "Chernobog" },
            { "barrage", "HVY Barrage" },
            { "halftrack", "Bravado Half-track" },
            { "apc", "HVY APC" },
            { "oppressor", "Pegassi Oppressor" },
            { "oppressor2", "Pegassi Oppressor Mk II" },
            { "squaddie", "Mammoth Squaddie" },
            { "winky", "Vapid Winky" },
            { "insurgent3", "HVY Insurgent Pick-Up Custom" },
            { "raiju", "Mammoth F-160 Raiju" },
            { "streamer216", "Mammoth Streamer216" },
            { "conada2", "Buckingham Weaponized Conada" },
            { "pounder2", "MTL Pounder Custom" },
            { "mule4", "Maibatsu Mule Custom" },
            { "phantom3", "JoBuilt Phantom Custom" },
            { "hauler2", "JoBuilt Hauler Custom" },
            { "phantom2", "JoBuilt Phantom Wedge" },
            { "mule3", "Maibatsu Mule" },
            { "boxville4", "Brute Boxville" },
            { "flatbed2", "MTL Flatbed" },
            { "stockade4", "Brute Stockade" },
            { "keitora", "Shitzu Keitora" },
            { "openwheel1", "Benefactor BR8" },
            { "openwheel2", "Progen PR4" },
            { "formula", "Ocelot R88" },
            { "formula2", "Declasse DR1" },
            { "raptor", "BF Raptor" },
            { "journey2", "Zirconium Journey II" },
            { "surfer3", "BF Surfer Custom" },
            { "youga3", "Bravado Youga Classic 4x4" },
            { "speedo4", "Vapid Speedo Custom" },
            { "youga2", "Bravado Youga Classic" },
            { "rumpo3", "Bravado Rumpo Custom" },
            { "minivan2", "Vapid Minivan Custom" },
            { "boxville6", "Brute Boxville" },
            { "riot2", "Brute RCV" },
            { "polgauntlet", "Bravado Gauntlet Interceptor" },
            { "police5", "Vapid Stanier LE Cruiser" },
            { "polbuffalo", "Bravado Buffalo Cruiser" },
            { "polbuffalo6", "Bravado Buffalo STX Pursuit" },
            { "policet3", "Vapid Police Transporter" },
            { "policeb2", "Western Police Bike" },
            { "polcoquette4", "Invetero Coquette D10 Cruiser" },
            { "polcaracara", "Vapid Caracara Cruiser" },
            { "polfaction2", "Willard Faction Cruiser" },
            { "polterminus", "Canis Terminus Cruiser" },
            { "inductor", "Coil Inductor" },
            { "inductor2", "Coil Junk Energy Inductor" },
            { "pbus2", "Vapid Festival Bus" },
            { "benson2", "Vapid Benson" },
            { "slamtruck", "Vapid Slamtruck" },
            { "wastelander", "MTL Wastelander" },
            { "towtruck4", "Vapid Tow Truck" },
            { "pizzaboy", "Pegassi Pizza Boy" },
            { "scramjet", "Declasse Scramjet" },
            { "vigilante", "Grotti Vigilante" },
            { "voltic2", "Coil Rocket Voltic" },
            { "toreador", "Pegassi Toreador" },
            { "jb7002", "Dewbauchee JB 700W" },
            { "deluxo", "Imponte Deluxo" },
            { "stromberg", "Ocelot Stromberg" },
            { "rrocket", "Western Rampant Rocket" },
            { "shotaro", "Nagasaki Shotaro" },
            { "dune5", "BF Ramp Buggy" },
        };

        internal static readonly Dictionary<string, int> Prices = new Dictionary<string, int>
        {
            { "brioso", 0 },
            { "brioso2", 0 },
            { "brioso3", 0 },
            { "weevil", 0 },
            { "club", 0 },
            { "kanjo", 0 },
            { "asbo", 0 },
            { "issi3", 0 },
            { "kanjosj", 0 },
            { "postlude", 0 },
            { "previon", 0 },
            { "windsor2", 0 },
            { "windsor", 0 },
            { "fr36", 0 },
            { "eurosx32", 0 },
            { "rhinehart", 0 },
            { "deity", 0 },
            { "cinquemila", 0 },
            { "tailgater2", 0 },
            { "warrener2", 0 },
            { "glendale2", 0 },
            { "stafford", 0 },
            { "schafter3", 0 },
            { "schafter4", 0 },
            { "limo2", 0 },
            { "schafter5", 0 },
            { "schafter6", 0 },
            { "cog552", 0 },
            { "cog55", 0 },
            { "cognoscenti2", 0 },
            { "cognoscenti", 0 },
            { "primo2", 0 },
            { "asterope2", 0 },
            { "impaler5", 0 },
            { "vorschlaghammer", 0 },
            { "chavosv6", 0 },
            { "hardy", 0 },
            { "minimus", 0 },
            { "sentinel6", 0 },
            { "issi8", 0 },
            { "granger2", 0 },
            { "iwagen", 0 },
            { "baller7", 0 },
            { "astron", 0 },
            { "jubilee", 0 },
            { "seminole2", 0 },
            { "landstalker2", 0 },
            { "rebla", 0 },
            { "novak", 0 },
            { "toros", 0 },
            { "stretch", 0 },
            { "contender", 0 },
            { "xls2", 0 },
            { "baller3", 0 },
            { "baller4", 0 },
            { "baller5", 0 },
            { "baller6", 0 },
            { "vivanite", 0 },
            { "aleutian", 0 },
            { "cavalcade3", 0 },
            { "baller8", 0 },
            { "dorado", 0 },
            { "castigator", 0 },
            { "astron2", 0 },
            { "everon3", 0 },
            { "woodlander", 0 },
            { "tahoma", 0 },
            { "tulip2", 0 },
            { "weevil2", 0 },
            { "vigero2", 0 },
            { "ruiner4", 0 },
            { "buffalo4", 0 },
            { "dominator7", 0 },
            { "dominator8", 0 },
            { "gauntlet5", 0 },
            { "manana2", 0 },
            { "dukes3", 0 },
            { "yosemite2", 0 },
            { "peyote2", 0 },
            { "gauntlet4", 0 },
            { "gauntlet3", 0 },
            { "vamos", 0 },
            { "deviant", 0 },
            { "tulip", 0 },
            { "clique", 0 },
            { "imperator", 0 },
            { "impaler", 0 },
            { "dominator3", 0 },
            { "ellie", 0 },
            { "hustler", 0 },
            { "hermes", 0 },
            { "yosemite", 0 },
            { "tampa3", 0 },
            { "ruiner2", 0 },
            { "sabregt2", 0 },
            { "virgo2", 0 },
            { "virgo3", 0 },
            { "faction3", 0 },
            { "tampa", 0 },
            { "nightshade", 0 },
            { "moonbeam2", 0 },
            { "moonbeam", 0 },
            { "faction2", 0 },
            { "faction", 0 },
            { "chino2", 0 },
            { "buccaneer2", 0 },
            { "coquette3", 0 },
            { "chino", 0 },
            { "vigero", 0 },
            { "slamvan2", 0 },
            { "clique2", 0 },
            { "buffalo5", 0 },
            { "vigero3", 0 },
            { "dominator9", 0 },
            { "impaler6", 0 },
            { "dominator10", 0 },
            { "arbitergt", 0 },
            { "tampa4", 0 },
            { "everon2", 0 },
            { "panthere", 0 },
            { "r300", 0 },
            { "sentinel4", 0 },
            { "tenf2", 0 },
            { "tenf", 0 },
            { "sm722", 0 },
            { "omnisegt", 0 },
            { "corsita", 0 },
            { "comet7", 0 },
            { "cypher", 0 },
            { "sultan3", 0 },
            { "growler", 0 },
            { "vectre", 0 },
            { "comet6", 0 },
            { "remus", 0 },
            { "jester4", 0 },
            { "rt3000", 0 },
            { "zr350", 0 },
            { "euros", 0 },
            { "futo2", 0 },
            { "italirsx", 0 },
            { "penumbra2", 0 },
            { "coquette4", 0 },
            { "sugoi", 0 },
            { "vstr", 0 },
            { "sultan2", 0 },
            { "imorgon", 0 },
            { "komoda", 0 },
            { "jugular", 0 },
            { "zion3", 0 },
            { "locust", 0 },
            { "nebula", 0 },
            { "neo", 0 },
            { "issi7", 0 },
            { "drafter", 0 },
            { "paragon", 0 },
            { "paragon2", 0 },
            { "schlagen", 0 },
            { "italigto", 0 },
            { "swinger", 0 },
            { "jester3", 0 },
            { "michelli", 0 },
            { "flashgt", 0 },
            { "gb200", 0 },
            { "hotring", 0 },
            { "comet5", 0 },
            { "z190", 0 },
            { "neon", 0 },
            { "revolter", 0 },
            { "gt500", 0 },
            { "viseris", 0 },
            { "savestra", 0 },
            { "streiter", 0 },
            { "sentinel3", 0 },
            { "raiden", 0 },
            { "pariah", 0 },
            { "comet4", 0 },
            { "rapidgt3", 0 },
            { "retinue", 0 },
            { "ardent", 0 },
            { "torero", 0 },
            { "cheetah2", 0 },
            { "turismo2", 0 },
            { "infernus2", 0 },
            { "ruston", 0 },
            { "specter2", 0 },
            { "specter", 0 },
            { "comet3", 0 },
            { "elegy", 0 },
            { "tampa2", 0 },
            { "lynx", 0 },
            { "tropos", 0 },
            { "omnis", 0 },
            { "seven70", 0 },
            { "bestiagts", 0 },
            { "mamba", 0 },
            { "verlierer2", 0 },
            { "feltzer3", 0 },
            { "casco", 0 },
            { "kuruma", 0 },
            { "kuruma2", 0 },
            { "stingertt", 0 },
            { "gauntlet6", 0 },
            { "coureur", 0 },
            { "coquette5", 0 },
            { "envisage", 0 },
            { "niobe", 0 },
            { "paragon3", 0 },
            { "banshee3", 0 },
            { "jester5", 0 },
            { "coquette6", 0 },
            { "s95", 0 },
            { "cheetah3", 0 },
            { "rapidgt4", 0 },
            { "sentinel5", 0 },
            { "astrale", 0 },
            { "gt750", 0 },
            { "itali2", 0 },
            { "virtue", 0 },
            { "entity3", 0 },
            { "lm87", 0 },
            { "torero2", 0 },
            { "zeno", 0 },
            { "ignus", 0 },
            { "champion", 0 },
            { "tigon", 0 },
            { "furia", 0 },
            { "zorrusso", 0 },
            { "krieger", 0 },
            { "emerus", 0 },
            { "s80", 0 },
            { "thrax", 0 },
            { "deveste", 0 },
            { "tyrant", 0 },
            { "tezeract", 0 },
            { "taipan", 0 },
            { "entity2", 0 },
            { "autarch", 0 },
            { "sc1", 0 },
            { "cyclone", 0 },
            { "visione", 0 },
            { "xa21", 0 },
            { "vagner", 0 },
            { "gp1", 0 },
            { "italigtb", 0 },
            { "italigtb2", 0 },
            { "nero", 0 },
            { "nero2", 0 },
            { "tempesta", 0 },
            { "penetrator", 0 },
            { "tyrus", 0 },
            { "le7b", 0 },
            { "sheava", 0 },
            { "pfister811", 0 },
            { "prototipo", 0 },
            { "reaper", 0 },
            { "fmj", 0 },
            { "sultanrs", 0 },
            { "banshee2", 0 },
            { "t20", 0 },
            { "osiris", 0 },
            { "turismo3", 0 },
            { "pipistrello", 0 },
            { "cyclone2", 0 },
            { "suzume", 0 },
            { "fmj2", 0 },
            { "luiva", 0 },
            { "xtreme", 0 },
            { "boor", 0 },
            { "draugur", 0 },
            { "patriot3", 0 },
            { "verus", 0 },
            { "yosemite3", 0 },
            { "outlaw", 0 },
            { "zhaba", 0 },
            { "everon", 0 },
            { "vagrant", 0 },
            { "hellion", 0 },
            { "caracara2", 0 },
            { "brutus", 0 },
            { "monster3", 0 },
            { "bruiser", 0 },
            { "freecrawler", 0 },
            { "menacer", 0 },
            { "caracara", 0 },
            { "kamacho", 0 },
            { "riata", 0 },
            { "nightshark", 0 },
            { "technical3", 0 },
            { "dune3", 0 },
            { "blazer5", 0 },
            { "blazer4", 0 },
            { "rallytruck", 0 },
            { "trophytruck", 0 },
            { "trophytruck2", 0 },
            { "brawler", 0 },
            { "technical", 0 },
            { "insurgent", 0 },
            { "guardian", 0 },
            { "l35", 0 },
            { "ratel", 0 },
            { "monstrociti", 0 },
            { "terminus", 0 },
            { "yosemite1500", 0 },
            { "firebolt", 0 },
            { "uranus", 0 },
            { "l352", 0 },
            { "powersurge", 0 },
            { "manchez3", 0 },
            { "reever", 0 },
            { "shinobi", 0 },
            { "manchez2", 0 },
            { "stryder", 0 },
            { "fcr2", 0 },
            { "fcr", 0 },
            { "diablous", 0 },
            { "diablous2", 0 },
            { "esskey", 0 },
            { "vortex", 0 },
            { "daemon2", 0 },
            { "zombiea", 0 },
            { "zombieb", 0 },
            { "wolfsbane", 0 },
            { "nightblade", 0 },
            { "manchez", 0 },
            { "hakuchou2", 0 },
            { "faggio", 0 },
            { "faggio3", 0 },
            { "defiler", 0 },
            { "chimera", 0 },
            { "avarus", 0 },
            { "cliffhanger", 0 },
            { "gargoyle", 0 },
            { "bf400", 0 },
            { "vindicator", 0 },
            { "lectro", 0 },
            { "enduro", 0 },
            { "longfin", 0 },
            { "toro", 0 },
            { "avisa", 0 },
            { "dinghy5", 0 },
            { "patrolboat", 0 },
            { "tug", 0 },
            { "conada", 0 },
            { "havok", 0 },
            { "volatus", 0 },
            { "supervolito", 0 },
            { "supervolito2", 0 },
            { "swift2", 0 },
            { "annihilator2", 0 },
            { "akula", 0 },
            { "hunter", 0 },
            { "valkyrie", 0 },
            { "savage", 0 },
            { "microlight", 0 },
            { "nimbus", 0 },
            { "luxor2", 0 },
            { "velum2", 0 },
            { "alkonost", 0 },
            { "strikeforce", 0 },
            { "avenger", 0 },
            { "volatol", 0 },
            { "nokota", 0 },
            { "seabreeze", 0 },
            { "pyro", 0 },
            { "mogul", 0 },
            { "howard", 0 },
            { "bombushka", 0 },
            { "molotok", 0 },
            { "tula", 0 },
            { "rogue", 0 },
            { "starling", 0 },
            { "alphaz1", 0 },
            { "hydra", 0 },
            { "vetir", 0 },
            { "scarab", 0 },
            { "terbyte", 0 },
            { "thruster", 0 },
            { "khanjali", 0 },
            { "chernobog", 0 },
            { "barrage", 0 },
            { "halftrack", 0 },
            { "apc", 0 },
            { "oppressor", 0 },
            { "oppressor2", 0 },
            { "squaddie", 0 },
            { "winky", 0 },
            { "insurgent3", 0 },
            { "raiju", 0 },
            { "streamer216", 0 },
            { "conada2", 0 },
            { "pounder2", 0 },
            { "mule4", 0 },
            { "phantom3", 0 },
            { "hauler2", 0 },
            { "phantom2", 0 },
            { "mule3", 0 },
            { "boxville4", 0 },
            { "flatbed2", 0 },
            { "stockade4", 0 },
            { "keitora", 0 },
            { "openwheel1", 0 },
            { "openwheel2", 0 },
            { "formula", 0 },
            { "formula2", 0 },
            { "raptor", 0 },
            { "journey2", 0 },
            { "surfer3", 0 },
            { "youga3", 0 },
            { "speedo4", 0 },
            { "youga2", 0 },
            { "rumpo3", 0 },
            { "minivan2", 0 },
            { "boxville6", 0 },
            { "riot2", 0 },
            { "polgauntlet", 0 },
            { "police5", 0 },
            { "polbuffalo", 0 },
            { "polbuffalo6", 0 },
            { "policet3", 0 },
            { "policeb2", 0 },
            { "polcoquette4", 0 },
            { "polcaracara", 0 },
            { "polfaction2", 0 },
            { "polterminus", 0 },
            { "inductor", 0 },
            { "inductor2", 0 },
            { "pbus2", 0 },
            { "benson2", 0 },
            { "slamtruck", 0 },
            { "wastelander", 0 },
            { "towtruck4", 0 },
            { "pizzaboy", 0 },
            { "scramjet", 0 },
            { "vigilante", 0 },
            { "voltic2", 0 },
            { "toreador", 0 },
            { "jb7002", 0 },
            { "deluxo", 0 },
            { "stromberg", 0 },
            { "rrocket", 0 },
            { "shotaro", 0 },
            { "dune5", 0 },
        };

        internal static readonly Dictionary<string, string> ClassNames = new Dictionary<string, string>
        {
            { "brioso", "Compacts" },
            { "brioso2", "Compacts" },
            { "brioso3", "Compacts" },
            { "weevil", "Compacts" },
            { "club", "Compacts" },
            { "kanjo", "Compacts" },
            { "asbo", "Compacts" },
            { "issi3", "Compacts" },
            { "kanjosj", "Coupes" },
            { "postlude", "Coupes" },
            { "previon", "Coupes" },
            { "windsor2", "Coupes" },
            { "windsor", "Coupes" },
            { "fr36", "Coupes" },
            { "eurosx32", "Coupes" },
            { "rhinehart", "Sedans" },
            { "deity", "Sedans" },
            { "cinquemila", "Sedans" },
            { "tailgater2", "Sedans" },
            { "warrener2", "Sedans" },
            { "glendale2", "Sedans" },
            { "stafford", "Sedans" },
            { "schafter3", "Sedans" },
            { "schafter4", "Sedans" },
            { "limo2", "Sedans" },
            { "schafter5", "Sedans" },
            { "schafter6", "Sedans" },
            { "cog552", "Sedans" },
            { "cog55", "Sedans" },
            { "cognoscenti2", "Sedans" },
            { "cognoscenti", "Sedans" },
            { "primo2", "Sedans" },
            { "asterope2", "Sedans" },
            { "impaler5", "Sedans" },
            { "vorschlaghammer", "Sedans" },
            { "chavosv6", "Sedans" },
            { "hardy", "Sedans" },
            { "minimus", "Sedans" },
            { "sentinel6", "Sedans" },
            { "issi8", "Suvs" },
            { "granger2", "Suvs" },
            { "iwagen", "Suvs" },
            { "baller7", "Suvs" },
            { "astron", "Suvs" },
            { "jubilee", "Suvs" },
            { "seminole2", "Suvs" },
            { "landstalker2", "Suvs" },
            { "rebla", "Suvs" },
            { "novak", "Suvs" },
            { "toros", "Suvs" },
            { "stretch", "Suvs" },
            { "contender", "Suvs" },
            { "xls2", "Suvs" },
            { "baller3", "Suvs" },
            { "baller4", "Suvs" },
            { "baller5", "Suvs" },
            { "baller6", "Suvs" },
            { "vivanite", "Suvs" },
            { "aleutian", "Suvs" },
            { "cavalcade3", "Suvs" },
            { "baller8", "Suvs" },
            { "dorado", "Suvs" },
            { "castigator", "Suvs" },
            { "astron2", "Suvs" },
            { "everon3", "Suvs" },
            { "woodlander", "Suvs" },
            { "tahoma", "Muscle" },
            { "tulip2", "Muscle" },
            { "weevil2", "Muscle" },
            { "vigero2", "Muscle" },
            { "ruiner4", "Muscle" },
            { "buffalo4", "Muscle" },
            { "dominator7", "Muscle" },
            { "dominator8", "Muscle" },
            { "gauntlet5", "Muscle" },
            { "manana2", "Muscle" },
            { "dukes3", "Muscle" },
            { "yosemite2", "Muscle" },
            { "peyote2", "Muscle" },
            { "gauntlet4", "Muscle" },
            { "gauntlet3", "Muscle" },
            { "vamos", "Muscle" },
            { "deviant", "Muscle" },
            { "tulip", "Muscle" },
            { "clique", "Muscle" },
            { "imperator", "Muscle" },
            { "impaler", "Muscle" },
            { "dominator3", "Muscle" },
            { "ellie", "Muscle" },
            { "hustler", "Muscle" },
            { "hermes", "Muscle" },
            { "yosemite", "Muscle" },
            { "tampa3", "Muscle" },
            { "ruiner2", "Muscle" },
            { "sabregt2", "Muscle" },
            { "virgo2", "Muscle" },
            { "virgo3", "Muscle" },
            { "faction3", "Muscle" },
            { "tampa", "Muscle" },
            { "nightshade", "Muscle" },
            { "moonbeam2", "Muscle" },
            { "moonbeam", "Muscle" },
            { "faction2", "Muscle" },
            { "faction", "Muscle" },
            { "chino2", "Muscle" },
            { "buccaneer2", "Muscle" },
            { "coquette3", "Muscle" },
            { "chino", "Muscle" },
            { "vigero", "Muscle" },
            { "slamvan2", "Muscle" },
            { "clique2", "Muscle" },
            { "buffalo5", "Muscle" },
            { "vigero3", "Muscle" },
            { "dominator9", "Muscle" },
            { "impaler6", "Muscle" },
            { "dominator10", "Muscle" },
            { "arbitergt", "Muscle" },
            { "tampa4", "Muscle" },
            { "everon2", "Sportsclassics" },
            { "panthere", "Sportsclassics" },
            { "r300", "Sportsclassics" },
            { "sentinel4", "Sportsclassics" },
            { "tenf2", "Sportsclassics" },
            { "tenf", "Sportsclassics" },
            { "sm722", "Sportsclassics" },
            { "omnisegt", "Sportsclassics" },
            { "corsita", "Sportsclassics" },
            { "comet7", "Sportsclassics" },
            { "cypher", "Sportsclassics" },
            { "sultan3", "Sportsclassics" },
            { "growler", "Sportsclassics" },
            { "vectre", "Sportsclassics" },
            { "comet6", "Sportsclassics" },
            { "remus", "Sportsclassics" },
            { "jester4", "Sportsclassics" },
            { "rt3000", "Sportsclassics" },
            { "zr350", "Sportsclassics" },
            { "euros", "Sportsclassics" },
            { "futo2", "Sportsclassics" },
            { "italirsx", "Sportsclassics" },
            { "penumbra2", "Sportsclassics" },
            { "coquette4", "Sportsclassics" },
            { "sugoi", "Sportsclassics" },
            { "vstr", "Sportsclassics" },
            { "sultan2", "Sportsclassics" },
            { "imorgon", "Sportsclassics" },
            { "komoda", "Sportsclassics" },
            { "jugular", "Sportsclassics" },
            { "zion3", "Sportsclassics" },
            { "locust", "Sportsclassics" },
            { "nebula", "Sportsclassics" },
            { "neo", "Sportsclassics" },
            { "issi7", "Sportsclassics" },
            { "drafter", "Sportsclassics" },
            { "paragon", "Sportsclassics" },
            { "paragon2", "Sportsclassics" },
            { "schlagen", "Sportsclassics" },
            { "italigto", "Sportsclassics" },
            { "swinger", "Sportsclassics" },
            { "jester3", "Sportsclassics" },
            { "michelli", "Sportsclassics" },
            { "flashgt", "Sportsclassics" },
            { "gb200", "Sportsclassics" },
            { "hotring", "Sportsclassics" },
            { "comet5", "Sportsclassics" },
            { "z190", "Sportsclassics" },
            { "neon", "Sportsclassics" },
            { "revolter", "Sportsclassics" },
            { "gt500", "Sportsclassics" },
            { "viseris", "Sportsclassics" },
            { "savestra", "Sportsclassics" },
            { "streiter", "Sportsclassics" },
            { "sentinel3", "Sportsclassics" },
            { "raiden", "Sportsclassics" },
            { "pariah", "Sportsclassics" },
            { "comet4", "Sportsclassics" },
            { "rapidgt3", "Sportsclassics" },
            { "retinue", "Sportsclassics" },
            { "ardent", "Sportsclassics" },
            { "torero", "Sportsclassics" },
            { "cheetah2", "Sportsclassics" },
            { "turismo2", "Sportsclassics" },
            { "infernus2", "Sportsclassics" },
            { "ruston", "Sportsclassics" },
            { "specter2", "Sportsclassics" },
            { "specter", "Sportsclassics" },
            { "comet3", "Sportsclassics" },
            { "elegy", "Sportsclassics" },
            { "tampa2", "Sportsclassics" },
            { "lynx", "Sportsclassics" },
            { "tropos", "Sportsclassics" },
            { "omnis", "Sportsclassics" },
            { "seven70", "Sportsclassics" },
            { "bestiagts", "Sportsclassics" },
            { "mamba", "Sportsclassics" },
            { "verlierer2", "Sportsclassics" },
            { "feltzer3", "Sportsclassics" },
            { "casco", "Sportsclassics" },
            { "kuruma", "Sportsclassics" },
            { "kuruma2", "Sportsclassics" },
            { "stingertt", "Sportsclassics" },
            { "gauntlet6", "Sportsclassics" },
            { "coureur", "Sportsclassics" },
            { "coquette5", "Sportsclassics" },
            { "envisage", "Sportsclassics" },
            { "niobe", "Sportsclassics" },
            { "paragon3", "Sportsclassics" },
            { "banshee3", "Sportsclassics" },
            { "jester5", "Sportsclassics" },
            { "coquette6", "Sportsclassics" },
            { "s95", "Sportsclassics" },
            { "cheetah3", "Sportsclassics" },
            { "rapidgt4", "Sportsclassics" },
            { "sentinel5", "Sportsclassics" },
            { "astrale", "Sportsclassics" },
            { "gt750", "Sportsclassics" },
            { "itali2", "Sportsclassics" },
            { "virtue", "Super" },
            { "entity3", "Super" },
            { "lm87", "Super" },
            { "torero2", "Super" },
            { "zeno", "Super" },
            { "ignus", "Super" },
            { "champion", "Super" },
            { "tigon", "Super" },
            { "furia", "Super" },
            { "zorrusso", "Super" },
            { "krieger", "Super" },
            { "emerus", "Super" },
            { "s80", "Super" },
            { "thrax", "Super" },
            { "deveste", "Super" },
            { "tyrant", "Super" },
            { "tezeract", "Super" },
            { "taipan", "Super" },
            { "entity2", "Super" },
            { "autarch", "Super" },
            { "sc1", "Super" },
            { "cyclone", "Super" },
            { "visione", "Super" },
            { "xa21", "Super" },
            { "vagner", "Super" },
            { "gp1", "Super" },
            { "italigtb", "Super" },
            { "italigtb2", "Super" },
            { "nero", "Super" },
            { "nero2", "Super" },
            { "tempesta", "Super" },
            { "penetrator", "Super" },
            { "tyrus", "Super" },
            { "le7b", "Super" },
            { "sheava", "Super" },
            { "pfister811", "Super" },
            { "prototipo", "Super" },
            { "reaper", "Super" },
            { "fmj", "Super" },
            { "sultanrs", "Super" },
            { "banshee2", "Super" },
            { "t20", "Super" },
            { "osiris", "Super" },
            { "turismo3", "Super" },
            { "pipistrello", "Super" },
            { "cyclone2", "Super" },
            { "suzume", "Super" },
            { "fmj2", "Super" },
            { "luiva", "Super" },
            { "xtreme", "Super" },
            { "boor", "Offroad" },
            { "draugur", "Offroad" },
            { "patriot3", "Offroad" },
            { "verus", "Offroad" },
            { "yosemite3", "Offroad" },
            { "outlaw", "Offroad" },
            { "zhaba", "Offroad" },
            { "everon", "Offroad" },
            { "vagrant", "Offroad" },
            { "hellion", "Offroad" },
            { "caracara2", "Offroad" },
            { "brutus", "Offroad" },
            { "monster3", "Offroad" },
            { "bruiser", "Offroad" },
            { "freecrawler", "Offroad" },
            { "menacer", "Offroad" },
            { "caracara", "Offroad" },
            { "kamacho", "Offroad" },
            { "riata", "Offroad" },
            { "nightshark", "Offroad" },
            { "technical3", "Offroad" },
            { "dune3", "Offroad" },
            { "blazer5", "Offroad" },
            { "blazer4", "Offroad" },
            { "rallytruck", "Offroad" },
            { "trophytruck", "Offroad" },
            { "trophytruck2", "Offroad" },
            { "brawler", "Offroad" },
            { "technical", "Offroad" },
            { "insurgent", "Offroad" },
            { "guardian", "Offroad" },
            { "l35", "Offroad" },
            { "ratel", "Offroad" },
            { "monstrociti", "Offroad" },
            { "terminus", "Offroad" },
            { "yosemite1500", "Offroad" },
            { "firebolt", "Offroad" },
            { "uranus", "Offroad" },
            { "l352", "Offroad" },
            { "powersurge", "Motorcycles" },
            { "manchez3", "Motorcycles" },
            { "reever", "Motorcycles" },
            { "shinobi", "Motorcycles" },
            { "manchez2", "Motorcycles" },
            { "stryder", "Motorcycles" },
            { "fcr2", "Motorcycles" },
            { "fcr", "Motorcycles" },
            { "diablous", "Motorcycles" },
            { "diablous2", "Motorcycles" },
            { "esskey", "Motorcycles" },
            { "vortex", "Motorcycles" },
            { "daemon2", "Motorcycles" },
            { "zombiea", "Motorcycles" },
            { "zombieb", "Motorcycles" },
            { "wolfsbane", "Motorcycles" },
            { "nightblade", "Motorcycles" },
            { "manchez", "Motorcycles" },
            { "hakuchou2", "Motorcycles" },
            { "faggio", "Motorcycles" },
            { "faggio3", "Motorcycles" },
            { "defiler", "Motorcycles" },
            { "chimera", "Motorcycles" },
            { "avarus", "Motorcycles" },
            { "cliffhanger", "Motorcycles" },
            { "gargoyle", "Motorcycles" },
            { "bf400", "Motorcycles" },
            { "vindicator", "Motorcycles" },
            { "lectro", "Motorcycles" },
            { "enduro", "Motorcycles" },
            { "longfin", "Boats" },
            { "toro", "Boats" },
            { "avisa", "Boats" },
            { "dinghy5", "Boats" },
            { "patrolboat", "Boats" },
            { "tug", "Boats" },
            { "conada", "Helicopters" },
            { "havok", "Helicopters" },
            { "volatus", "Helicopters" },
            { "supervolito", "Helicopters" },
            { "supervolito2", "Helicopters" },
            { "swift2", "Helicopters" },
            { "annihilator2", "Helicopters" },
            { "akula", "Helicopters" },
            { "hunter", "Helicopters" },
            { "valkyrie", "Helicopters" },
            { "savage", "Helicopters" },
            { "microlight", "Planes" },
            { "nimbus", "Planes" },
            { "luxor2", "Planes" },
            { "velum2", "Planes" },
            { "alkonost", "Planes" },
            { "strikeforce", "Planes" },
            { "avenger", "Planes" },
            { "volatol", "Planes" },
            { "nokota", "Planes" },
            { "seabreeze", "Planes" },
            { "pyro", "Planes" },
            { "mogul", "Planes" },
            { "howard", "Planes" },
            { "bombushka", "Planes" },
            { "molotok", "Planes" },
            { "tula", "Planes" },
            { "rogue", "Planes" },
            { "starling", "Planes" },
            { "alphaz1", "Planes" },
            { "hydra", "Planes" },
            { "vetir", "Military" },
            { "scarab", "Military" },
            { "terbyte", "Military" },
            { "thruster", "Military" },
            { "khanjali", "Military" },
            { "chernobog", "Military" },
            { "barrage", "Military" },
            { "halftrack", "Military" },
            { "apc", "Military" },
            { "oppressor", "Military" },
            { "oppressor2", "Military" },
            { "squaddie", "Military" },
            { "winky", "Military" },
            { "insurgent3", "Military" },
            { "raiju", "Military" },
            { "streamer216", "Military" },
            { "conada2", "Military" },
            { "pounder2", "Industrial" },
            { "mule4", "Industrial" },
            { "phantom3", "Industrial" },
            { "hauler2", "Industrial" },
            { "phantom2", "Industrial" },
            { "mule3", "Industrial" },
            { "boxville4", "Industrial" },
            { "flatbed2", "Industrial" },
            { "stockade4", "Industrial" },
            { "keitora", "Industrial" },
            { "openwheel1", "Openwheel" },
            { "openwheel2", "Openwheel" },
            { "formula", "Openwheel" },
            { "formula2", "Openwheel" },
            { "raptor", "Openwheel" },
            { "journey2", "Vans" },
            { "surfer3", "Vans" },
            { "youga3", "Vans" },
            { "speedo4", "Vans" },
            { "youga2", "Vans" },
            { "rumpo3", "Vans" },
            { "minivan2", "Vans" },
            { "boxville6", "Vans" },
            { "riot2", "Emergency" },
            { "polgauntlet", "Emergency" },
            { "police5", "Emergency" },
            { "polbuffalo", "Emergency" },
            { "polbuffalo6", "Emergency" },
            { "policet3", "Emergency" },
            { "policeb2", "Emergency" },
            { "polcoquette4", "Emergency" },
            { "polcaracara", "Emergency" },
            { "polfaction2", "Emergency" },
            { "polterminus", "Emergency" },
            { "inductor", "Cycles" },
            { "inductor2", "Cycles" },
            { "pbus2", "Service" },
            { "benson2", "Service" },
            { "slamtruck", "Service" },
            { "wastelander", "Service" },
            { "towtruck4", "Service" },
            { "pizzaboy", "Service" },
            { "scramjet", "Special" },
            { "vigilante", "Special" },
            { "voltic2", "Special" },
            { "toreador", "Special" },
            { "jb7002", "Special" },
            { "deluxo", "Special" },
            { "stromberg", "Special" },
            { "rrocket", "Special" },
            { "shotaro", "Special" },
            { "dune5", "Special" },
        };

        internal static readonly Dictionary<string, string> PreviewDict = new Dictionary<string, string>
        {
            { "akula", "allin1_prev_01" },
            { "aleutian", "allin1_prev_01" },
            { "alkonost", "allin1_prev_01" },
            { "alphaz1", "allin1_prev_01" },
            { "annihilator2", "allin1_prev_01" },
            { "apc", "allin1_prev_01" },
            { "arbitergt", "allin1_prev_01" },
            { "ardent", "allin1_prev_01" },
            { "asbo", "allin1_prev_01" },
            { "asterope2", "allin1_prev_01" },
            { "astrale", "allin1_prev_01" },
            { "astron", "allin1_prev_01" },
            { "astron2", "allin1_prev_01" },
            { "autarch", "allin1_prev_01" },
            { "avarus", "allin1_prev_01" },
            { "avenger", "allin1_prev_01" },
            { "avisa", "allin1_prev_01" },
            { "baller3", "allin1_prev_01" },
            { "baller4", "allin1_prev_01" },
            { "baller5", "allin1_prev_01" },
            { "baller6", "allin1_prev_01" },
            { "baller7", "allin1_prev_01" },
            { "baller8", "allin1_prev_01" },
            { "banshee2", "allin1_prev_01" },
            { "banshee3", "allin1_prev_01" },
            { "barrage", "allin1_prev_01" },
            { "benson2", "allin1_prev_01" },
            { "bestiagts", "allin1_prev_01" },
            { "bf400", "allin1_prev_01" },
            { "blazer4", "allin1_prev_01" },
            { "blazer5", "allin1_prev_01" },
            { "bombushka", "allin1_prev_01" },
            { "boor", "allin1_prev_01" },
            { "boxville4", "allin1_prev_01" },
            { "boxville6", "allin1_prev_01" },
            { "brawler", "allin1_prev_01" },
            { "brioso", "allin1_prev_01" },
            { "brioso2", "allin1_prev_01" },
            { "brioso3", "allin1_prev_01" },
            { "bruiser", "allin1_prev_01" },
            { "brutus", "allin1_prev_01" },
            { "buccaneer2", "allin1_prev_01" },
            { "buffalo4", "allin1_prev_01" },
            { "buffalo5", "allin1_prev_01" },
            { "caracara", "allin1_prev_01" },
            { "caracara2", "allin1_prev_01" },
            { "casco", "allin1_prev_01" },
            { "castigator", "allin1_prev_01" },
            { "cavalcade3", "allin1_prev_01" },
            { "champion", "allin1_prev_01" },
            { "chavosv6", "allin1_prev_01" },
            { "cheetah2", "allin1_prev_01" },
            { "cheetah3", "allin1_prev_01" },
            { "chernobog", "allin1_prev_01" },
            { "chimera", "allin1_prev_01" },
            { "chino", "allin1_prev_01" },
            { "chino2", "allin1_prev_01" },
            { "cinquemila", "allin1_prev_01" },
            { "cliffhanger", "allin1_prev_01" },
            { "clique", "allin1_prev_01" },
            { "clique2", "allin1_prev_01" },
            { "club", "allin1_prev_01" },
            { "cog55", "allin1_prev_01" },
            { "cog552", "allin1_prev_01" },
            { "cognoscenti", "allin1_prev_01" },
            { "cognoscenti2", "allin1_prev_01" },
            { "comet3", "allin1_prev_01" },
            { "comet4", "allin1_prev_01" },
            { "comet5", "allin1_prev_01" },
            { "comet6", "allin1_prev_01" },
            { "comet7", "allin1_prev_01" },
            { "conada", "allin1_prev_01" },
            { "conada2", "allin1_prev_01" },
            { "contender", "allin1_prev_01" },
            { "coquette3", "allin1_prev_01" },
            { "coquette4", "allin1_prev_01" },
            { "coquette5", "allin1_prev_01" },
            { "coquette6", "allin1_prev_01" },
            { "corsita", "allin1_prev_01" },
            { "coureur", "allin1_prev_01" },
            { "cyclone", "allin1_prev_01" },
            { "cyclone2", "allin1_prev_01" },
            { "cypher", "allin1_prev_01" },
            { "daemon2", "allin1_prev_01" },
            { "defiler", "allin1_prev_01" },
            { "deity", "allin1_prev_01" },
            { "deluxo", "allin1_prev_01" },
            { "deveste", "allin1_prev_01" },
            { "deviant", "allin1_prev_01" },
            { "diablous", "allin1_prev_02" },
            { "diablous2", "allin1_prev_02" },
            { "dinghy5", "allin1_prev_02" },
            { "dominator10", "allin1_prev_02" },
            { "dominator3", "allin1_prev_02" },
            { "dominator7", "allin1_prev_02" },
            { "dominator8", "allin1_prev_02" },
            { "dominator9", "allin1_prev_02" },
            { "dorado", "allin1_prev_02" },
            { "drafter", "allin1_prev_02" },
            { "draugur", "allin1_prev_02" },
            { "dukes3", "allin1_prev_02" },
            { "dune3", "allin1_prev_02" },
            { "dune5", "allin1_prev_02" },
            { "elegy", "allin1_prev_02" },
            { "ellie", "allin1_prev_02" },
            { "emerus", "allin1_prev_02" },
            { "enduro", "allin1_prev_02" },
            { "entity2", "allin1_prev_02" },
            { "entity3", "allin1_prev_02" },
            { "envisage", "allin1_prev_02" },
            { "esskey", "allin1_prev_02" },
            { "euros", "allin1_prev_02" },
            { "eurosx32", "allin1_prev_02" },
            { "everon", "allin1_prev_02" },
            { "everon2", "allin1_prev_02" },
            { "everon3", "allin1_prev_02" },
            { "faction", "allin1_prev_02" },
            { "faction2", "allin1_prev_02" },
            { "faction3", "allin1_prev_02" },
            { "faggio", "allin1_prev_02" },
            { "faggio3", "allin1_prev_02" },
            { "fcr", "allin1_prev_02" },
            { "fcr2", "allin1_prev_02" },
            { "feltzer3", "allin1_prev_02" },
            { "firebolt", "allin1_prev_02" },
            { "flashgt", "allin1_prev_02" },
            { "flatbed2", "allin1_prev_02" },
            { "fmj", "allin1_prev_02" },
            { "fmj2", "allin1_prev_02" },
            { "formula", "allin1_prev_02" },
            { "formula2", "allin1_prev_02" },
            { "fr36", "allin1_prev_02" },
            { "freecrawler", "allin1_prev_02" },
            { "furia", "allin1_prev_02" },
            { "futo2", "allin1_prev_02" },
            { "gargoyle", "allin1_prev_02" },
            { "gauntlet3", "allin1_prev_02" },
            { "gauntlet4", "allin1_prev_02" },
            { "gauntlet5", "allin1_prev_02" },
            { "gauntlet6", "allin1_prev_02" },
            { "gb200", "allin1_prev_02" },
            { "glendale2", "allin1_prev_02" },
            { "gp1", "allin1_prev_02" },
            { "granger2", "allin1_prev_02" },
            { "growler", "allin1_prev_02" },
            { "gt500", "allin1_prev_02" },
            { "gt750", "allin1_prev_02" },
            { "guardian", "allin1_prev_02" },
            { "hakuchou2", "allin1_prev_02" },
            { "halftrack", "allin1_prev_02" },
            { "hardy", "allin1_prev_02" },
            { "hauler2", "allin1_prev_02" },
            { "havok", "allin1_prev_02" },
            { "hellion", "allin1_prev_02" },
            { "hermes", "allin1_prev_02" },
            { "hotring", "allin1_prev_02" },
            { "howard", "allin1_prev_02" },
            { "hunter", "allin1_prev_02" },
            { "hustler", "allin1_prev_02" },
            { "hydra", "allin1_prev_02" },
            { "ignus", "allin1_prev_02" },
            { "imorgon", "allin1_prev_02" },
            { "impaler", "allin1_prev_02" },
            { "impaler5", "allin1_prev_02" },
            { "impaler6", "allin1_prev_02" },
            { "imperator", "allin1_prev_02" },
            { "inductor", "allin1_prev_02" },
            { "inductor2", "allin1_prev_02" },
            { "infernus2", "allin1_prev_02" },
            { "insurgent", "allin1_prev_02" },
            { "insurgent3", "allin1_prev_02" },
            { "issi3", "allin1_prev_02" },
            { "issi7", "allin1_prev_02" },
            { "issi8", "allin1_prev_02" },
            { "itali2", "allin1_prev_02" },
            { "italigtb", "allin1_prev_02" },
            { "italigtb2", "allin1_prev_02" },
            { "italigto", "allin1_prev_02" },
            { "italirsx", "allin1_prev_03" },
            { "iwagen", "allin1_prev_03" },
            { "jb7002", "allin1_prev_03" },
            { "jester3", "allin1_prev_03" },
            { "jester4", "allin1_prev_03" },
            { "jester5", "allin1_prev_03" },
            { "journey2", "allin1_prev_03" },
            { "jubilee", "allin1_prev_03" },
            { "jugular", "allin1_prev_03" },
            { "kamacho", "allin1_prev_03" },
            { "kanjo", "allin1_prev_03" },
            { "kanjosj", "allin1_prev_03" },
            { "keitora", "allin1_prev_03" },
            { "khanjali", "allin1_prev_03" },
            { "komoda", "allin1_prev_03" },
            { "krieger", "allin1_prev_03" },
            { "kuruma", "allin1_prev_03" },
            { "kuruma2", "allin1_prev_03" },
            { "l35", "allin1_prev_03" },
            { "l352", "allin1_prev_03" },
            { "landstalker2", "allin1_prev_03" },
            { "le7b", "allin1_prev_03" },
            { "lectro", "allin1_prev_03" },
            { "limo2", "allin1_prev_03" },
            { "lm87", "allin1_prev_03" },
            { "locust", "allin1_prev_03" },
            { "longfin", "allin1_prev_03" },
            { "luiva", "allin1_prev_03" },
            { "luxor2", "allin1_prev_03" },
            { "lynx", "allin1_prev_03" },
            { "mamba", "allin1_prev_03" },
            { "manana2", "allin1_prev_03" },
            { "manchez", "allin1_prev_03" },
            { "manchez2", "allin1_prev_03" },
            { "manchez3", "allin1_prev_03" },
            { "menacer", "allin1_prev_03" },
            { "michelli", "allin1_prev_03" },
            { "microlight", "allin1_prev_03" },
            { "minimus", "allin1_prev_03" },
            { "minivan2", "allin1_prev_03" },
            { "mogul", "allin1_prev_03" },
            { "molotok", "allin1_prev_03" },
            { "monster3", "allin1_prev_03" },
            { "monstrociti", "allin1_prev_03" },
            { "moonbeam", "allin1_prev_03" },
            { "moonbeam2", "allin1_prev_03" },
            { "mule3", "allin1_prev_03" },
            { "mule4", "allin1_prev_03" },
            { "nebula", "allin1_prev_03" },
            { "neo", "allin1_prev_03" },
            { "neon", "allin1_prev_03" },
            { "nero", "allin1_prev_03" },
            { "nero2", "allin1_prev_03" },
            { "nightblade", "allin1_prev_03" },
            { "nightshade", "allin1_prev_03" },
            { "nightshark", "allin1_prev_03" },
            { "nimbus", "allin1_prev_03" },
            { "niobe", "allin1_prev_03" },
            { "nokota", "allin1_prev_03" },
            { "novak", "allin1_prev_03" },
            { "omnis", "allin1_prev_03" },
            { "omnisegt", "allin1_prev_03" },
            { "openwheel1", "allin1_prev_03" },
            { "openwheel2", "allin1_prev_03" },
            { "oppressor", "allin1_prev_03" },
            { "oppressor2", "allin1_prev_03" },
            { "osiris", "allin1_prev_03" },
            { "outlaw", "allin1_prev_03" },
            { "panthere", "allin1_prev_03" },
            { "paragon", "allin1_prev_03" },
            { "paragon2", "allin1_prev_03" },
            { "paragon3", "allin1_prev_03" },
            { "pariah", "allin1_prev_03" },
            { "patriot3", "allin1_prev_03" },
            { "patrolboat", "allin1_prev_03" },
            { "pbus2", "allin1_prev_03" },
            { "penetrator", "allin1_prev_03" },
            { "penumbra2", "allin1_prev_03" },
            { "peyote2", "allin1_prev_03" },
            { "pfister811", "allin1_prev_03" },
            { "phantom2", "allin1_prev_03" },
            { "phantom3", "allin1_prev_03" },
            { "pipistrello", "allin1_prev_03" },
            { "pizzaboy", "allin1_prev_03" },
            { "polbuffalo", "allin1_prev_03" },
            { "polbuffalo6", "allin1_prev_03" },
            { "polcaracara", "allin1_prev_03" },
            { "polcoquette4", "allin1_prev_03" },
            { "polfaction2", "allin1_prev_03" },
            { "polgauntlet", "allin1_prev_04" },
            { "police5", "allin1_prev_04" },
            { "policeb2", "allin1_prev_04" },
            { "policet3", "allin1_prev_04" },
            { "polterminus", "allin1_prev_04" },
            { "postlude", "allin1_prev_04" },
            { "pounder2", "allin1_prev_04" },
            { "powersurge", "allin1_prev_04" },
            { "previon", "allin1_prev_04" },
            { "primo2", "allin1_prev_04" },
            { "prototipo", "allin1_prev_04" },
            { "pyro", "allin1_prev_04" },
            { "r300", "allin1_prev_04" },
            { "raiden", "allin1_prev_04" },
            { "raiju", "allin1_prev_04" },
            { "rallytruck", "allin1_prev_04" },
            { "rapidgt3", "allin1_prev_04" },
            { "rapidgt4", "allin1_prev_04" },
            { "raptor", "allin1_prev_04" },
            { "ratel", "allin1_prev_04" },
            { "reaper", "allin1_prev_04" },
            { "rebla", "allin1_prev_04" },
            { "reever", "allin1_prev_04" },
            { "remus", "allin1_prev_04" },
            { "retinue", "allin1_prev_04" },
            { "revolter", "allin1_prev_04" },
            { "rhinehart", "allin1_prev_04" },
            { "riata", "allin1_prev_04" },
            { "riot2", "allin1_prev_04" },
            { "rogue", "allin1_prev_04" },
            { "rrocket", "allin1_prev_04" },
            { "rt3000", "allin1_prev_04" },
            { "ruiner2", "allin1_prev_04" },
            { "ruiner4", "allin1_prev_04" },
            { "rumpo3", "allin1_prev_04" },
            { "ruston", "allin1_prev_04" },
            { "s80", "allin1_prev_04" },
            { "s95", "allin1_prev_04" },
            { "sabregt2", "allin1_prev_04" },
            { "savage", "allin1_prev_04" },
            { "savestra", "allin1_prev_04" },
            { "sc1", "allin1_prev_04" },
            { "scarab", "allin1_prev_04" },
            { "schafter3", "allin1_prev_04" },
            { "schafter4", "allin1_prev_04" },
            { "schafter5", "allin1_prev_04" },
            { "schafter6", "allin1_prev_04" },
            { "schlagen", "allin1_prev_04" },
            { "scramjet", "allin1_prev_04" },
            { "seabreeze", "allin1_prev_04" },
            { "seminole2", "allin1_prev_04" },
            { "sentinel3", "allin1_prev_04" },
            { "sentinel4", "allin1_prev_04" },
            { "sentinel5", "allin1_prev_04" },
            { "sentinel6", "allin1_prev_04" },
            { "seven70", "allin1_prev_04" },
            { "sheava", "allin1_prev_04" },
            { "shinobi", "allin1_prev_04" },
            { "shotaro", "allin1_prev_04" },
            { "slamtruck", "allin1_prev_04" },
            { "slamvan2", "allin1_prev_04" },
            { "sm722", "allin1_prev_04" },
            { "specter", "allin1_prev_04" },
            { "specter2", "allin1_prev_04" },
            { "speedo4", "allin1_prev_04" },
            { "squaddie", "allin1_prev_04" },
            { "stafford", "allin1_prev_04" },
            { "starling", "allin1_prev_04" },
            { "stingertt", "allin1_prev_04" },
            { "stockade4", "allin1_prev_04" },
            { "streamer216", "allin1_prev_04" },
            { "streiter", "allin1_prev_04" },
            { "stretch", "allin1_prev_04" },
            { "strikeforce", "allin1_prev_04" },
            { "stromberg", "allin1_prev_04" },
            { "stryder", "allin1_prev_04" },
            { "sugoi", "allin1_prev_04" },
            { "sultan2", "allin1_prev_04" },
            { "sultan3", "allin1_prev_04" },
            { "sultanrs", "allin1_prev_04" },
            { "supervolito", "allin1_prev_04" },
            { "supervolito2", "allin1_prev_04" },
            { "surfer3", "allin1_prev_04" },
            { "suzume", "allin1_prev_04" },
            { "swift2", "allin1_prev_04" },
            { "swinger", "allin1_prev_04" },
            { "t20", "allin1_prev_04" },
            { "tahoma", "allin1_prev_04" },
            { "tailgater2", "allin1_prev_04" },
            { "taipan", "allin1_prev_05" },
            { "tampa", "allin1_prev_05" },
            { "tampa2", "allin1_prev_05" },
            { "tampa3", "allin1_prev_05" },
            { "tampa4", "allin1_prev_05" },
            { "technical", "allin1_prev_05" },
            { "technical3", "allin1_prev_05" },
            { "tempesta", "allin1_prev_05" },
            { "tenf", "allin1_prev_05" },
            { "tenf2", "allin1_prev_05" },
            { "terbyte", "allin1_prev_05" },
            { "terminus", "allin1_prev_05" },
            { "tezeract", "allin1_prev_05" },
            { "thrax", "allin1_prev_05" },
            { "thruster", "allin1_prev_05" },
            { "tigon", "allin1_prev_05" },
            { "toreador", "allin1_prev_05" },
            { "torero", "allin1_prev_05" },
            { "torero2", "allin1_prev_05" },
            { "toro", "allin1_prev_05" },
            { "toros", "allin1_prev_05" },
            { "towtruck4", "allin1_prev_05" },
            { "trophytruck", "allin1_prev_05" },
            { "trophytruck2", "allin1_prev_05" },
            { "tropos", "allin1_prev_05" },
            { "tug", "allin1_prev_05" },
            { "tula", "allin1_prev_05" },
            { "tulip", "allin1_prev_05" },
            { "tulip2", "allin1_prev_05" },
            { "turismo2", "allin1_prev_05" },
            { "turismo3", "allin1_prev_05" },
            { "tyrant", "allin1_prev_05" },
            { "tyrus", "allin1_prev_05" },
            { "uranus", "allin1_prev_05" },
            { "vagner", "allin1_prev_05" },
            { "vagrant", "allin1_prev_05" },
            { "valkyrie", "allin1_prev_05" },
            { "vamos", "allin1_prev_05" },
            { "vectre", "allin1_prev_05" },
            { "velum2", "allin1_prev_05" },
            { "verlierer2", "allin1_prev_05" },
            { "verus", "allin1_prev_05" },
            { "vetir", "allin1_prev_05" },
            { "vigero", "allin1_prev_05" },
            { "vigero2", "allin1_prev_05" },
            { "vigero3", "allin1_prev_05" },
            { "vigilante", "allin1_prev_05" },
            { "vindicator", "allin1_prev_05" },
            { "virgo2", "allin1_prev_05" },
            { "virgo3", "allin1_prev_05" },
            { "virtue", "allin1_prev_05" },
            { "viseris", "allin1_prev_05" },
            { "visione", "allin1_prev_05" },
            { "vivanite", "allin1_prev_05" },
            { "volatol", "allin1_prev_05" },
            { "volatus", "allin1_prev_05" },
            { "voltic2", "allin1_prev_05" },
            { "vorschlaghammer", "allin1_prev_05" },
            { "vortex", "allin1_prev_05" },
            { "vstr", "allin1_prev_05" },
            { "warrener2", "allin1_prev_05" },
            { "wastelander", "allin1_prev_05" },
            { "weevil", "allin1_prev_05" },
            { "weevil2", "allin1_prev_05" },
            { "windsor", "allin1_prev_05" },
            { "windsor2", "allin1_prev_05" },
            { "winky", "allin1_prev_05" },
            { "wolfsbane", "allin1_prev_05" },
            { "woodlander", "allin1_prev_05" },
            { "xa21", "allin1_prev_05" },
            { "xls2", "allin1_prev_05" },
            { "xtreme", "allin1_prev_05" },
            { "yosemite", "allin1_prev_05" },
            { "yosemite1500", "allin1_prev_05" },
            { "yosemite2", "allin1_prev_05" },
            { "yosemite3", "allin1_prev_05" },
            { "youga2", "allin1_prev_05" },
            { "youga3", "allin1_prev_05" },
            { "z190", "allin1_prev_05" },
            { "zeno", "allin1_prev_05" },
            { "zhaba", "allin1_prev_05" },
            { "zion3", "allin1_prev_05" },
            { "zombiea", "allin1_prev_05" },
            { "zombieb", "allin1_prev_05" },
            { "zorrusso", "allin1_prev_05" },
            { "zr350", "allin1_prev_05" },
        };
    }
}
