// WeaponList.cs - Auto-generated from data/weapons.toml + prices_weapons.toml
// 101 GTA Online weapons by category.
using System.Collections.Generic;

namespace ALLIN1
{
    internal static class WeaponList
    {
        internal static readonly string[] All = {
            "WEAPON_PISTOL",
            "WEAPON_PISTOL_MK2",
            "WEAPON_COMBATPISTOL",
            "WEAPON_APPISTOL",
            "WEAPON_STUNGUN",
            "WEAPON_PISTOL50",
            "WEAPON_SNSPISTOL",
            "WEAPON_SNSPISTOL_MK2",
            "WEAPON_HEAVYPISTOL",
            "WEAPON_VINTAGEPISTOL",
            "WEAPON_FLAREGUN",
            "WEAPON_MARKSMANPISTOL",
            "WEAPON_REVOLVER",
            "WEAPON_REVOLVER_MK2",
            "WEAPON_DOUBLEACTION",
            "WEAPON_RAYPISTOL",
            "WEAPON_CERAMICPISTOL",
            "WEAPON_NAVYREVOLVER",
            "WEAPON_GADGETPISTOL",
            "WEAPON_MICROSMG",
            "WEAPON_SMG",
            "WEAPON_SMG_MK2",
            "WEAPON_ASSAULTSMG",
            "WEAPON_COMBATPDW",
            "WEAPON_MACHINEPISTOL",
            "WEAPON_MINISMG",
            "WEAPON_RAYCARBINE",
            "WEAPON_PUMPSHOTGUN",
            "WEAPON_PUMPSHOTGUN_MK2",
            "WEAPON_SAWNOFFSHOTGUN",
            "WEAPON_ASSAULTSHOTGUN",
            "WEAPON_BULLPUPSHOTGUN",
            "WEAPON_MUSKET",
            "WEAPON_HEAVYSHOTGUN",
            "WEAPON_DBSHOTGUN",
            "WEAPON_AUTOSHOTGUN",
            "WEAPON_COMBATSHOTGUN",
            "WEAPON_ASSAULTRIFLE",
            "WEAPON_ASSAULTRIFLE_MK2",
            "WEAPON_CARBINERIFLE",
            "WEAPON_CARBINERIFLE_MK2",
            "WEAPON_ADVANCEDRIFLE",
            "WEAPON_SPECIALCARBINE",
            "WEAPON_SPECIALCARBINE_MK2",
            "WEAPON_BULLPUPRIFLE",
            "WEAPON_BULLPUPRIFLE_MK2",
            "WEAPON_COMPACTRIFLE",
            "WEAPON_MILITARYRIFLE",
            "WEAPON_HEAVYRIFLE",
            "WEAPON_TACTICALRIFLE",
            "WEAPON_MG",
            "WEAPON_COMBATMG",
            "WEAPON_COMBATMG_MK2",
            "WEAPON_GUSENBERG",
            "WEAPON_SNIPERRIFLE",
            "WEAPON_HEAVYSNIPER",
            "WEAPON_HEAVYSNIPER_MK2",
            "WEAPON_MARKSMANRIFLE",
            "WEAPON_MARKSMANRIFLE_MK2",
            "WEAPON_PRECISIONRIFLE",
            "WEAPON_RPG",
            "WEAPON_GRENADELAUNCHER",
            "WEAPON_MINIGUN",
            "WEAPON_FIREWORK",
            "WEAPON_RAILGUN",
            "WEAPON_HOMINGLAUNCHER",
            "WEAPON_COMPACTLAUNCHER",
            "WEAPON_RAYMINIGUN",
            "WEAPON_EMPLAUNCHER",
            "WEAPON_KNIFE",
            "WEAPON_NIGHTSTICK",
            "WEAPON_HAMMER",
            "WEAPON_BAT",
            "WEAPON_GOLFCLUB",
            "WEAPON_CROWBAR",
            "WEAPON_BOTTLE",
            "WEAPON_DAGGER",
            "WEAPON_HATCHET",
            "WEAPON_KNUCKLE",
            "WEAPON_MACHETE",
            "WEAPON_FLASHLIGHT",
            "WEAPON_SWITCHBLADE",
            "WEAPON_POOLCUE",
            "WEAPON_WRENCH",
            "WEAPON_BATTLEAXE",
            "WEAPON_STONE_HATCHET",
            "WEAPON_GRENADE",
            "WEAPON_BZGAS",
            "WEAPON_MOLOTOV",
            "WEAPON_STICKYBOMB",
            "WEAPON_PROXMINE",
            "WEAPON_SNOWBALL",
            "WEAPON_PIPEBOMB",
            "WEAPON_BALL",
            "WEAPON_SMOKEGRENADE",
            "WEAPON_FLARE",
            "WEAPON_PETROLCAN",
            "WEAPON_FIREEXTINGUISHER",
            "WEAPON_HAZARDCAN",
            "WEAPON_FERTILIZERCAN",
            "WEAPON_ACIDPACKAGE",
        };

        internal static readonly string[] Pistols = {
            "WEAPON_PISTOL",
            "WEAPON_PISTOL_MK2",
            "WEAPON_COMBATPISTOL",
            "WEAPON_APPISTOL",
            "WEAPON_STUNGUN",
            "WEAPON_PISTOL50",
            "WEAPON_SNSPISTOL",
            "WEAPON_SNSPISTOL_MK2",
            "WEAPON_HEAVYPISTOL",
            "WEAPON_VINTAGEPISTOL",
            "WEAPON_FLAREGUN",
            "WEAPON_MARKSMANPISTOL",
            "WEAPON_REVOLVER",
            "WEAPON_REVOLVER_MK2",
            "WEAPON_DOUBLEACTION",
            "WEAPON_RAYPISTOL",
            "WEAPON_CERAMICPISTOL",
            "WEAPON_NAVYREVOLVER",
            "WEAPON_GADGETPISTOL",
        };

        internal static readonly string[] Smgs = {
            "WEAPON_MICROSMG",
            "WEAPON_SMG",
            "WEAPON_SMG_MK2",
            "WEAPON_ASSAULTSMG",
            "WEAPON_COMBATPDW",
            "WEAPON_MACHINEPISTOL",
            "WEAPON_MINISMG",
            "WEAPON_RAYCARBINE",
        };

        internal static readonly string[] Shotguns = {
            "WEAPON_PUMPSHOTGUN",
            "WEAPON_PUMPSHOTGUN_MK2",
            "WEAPON_SAWNOFFSHOTGUN",
            "WEAPON_ASSAULTSHOTGUN",
            "WEAPON_BULLPUPSHOTGUN",
            "WEAPON_MUSKET",
            "WEAPON_HEAVYSHOTGUN",
            "WEAPON_DBSHOTGUN",
            "WEAPON_AUTOSHOTGUN",
            "WEAPON_COMBATSHOTGUN",
        };

        internal static readonly string[] Rifles = {
            "WEAPON_ASSAULTRIFLE",
            "WEAPON_ASSAULTRIFLE_MK2",
            "WEAPON_CARBINERIFLE",
            "WEAPON_CARBINERIFLE_MK2",
            "WEAPON_ADVANCEDRIFLE",
            "WEAPON_SPECIALCARBINE",
            "WEAPON_SPECIALCARBINE_MK2",
            "WEAPON_BULLPUPRIFLE",
            "WEAPON_BULLPUPRIFLE_MK2",
            "WEAPON_COMPACTRIFLE",
            "WEAPON_MILITARYRIFLE",
            "WEAPON_HEAVYRIFLE",
            "WEAPON_TACTICALRIFLE",
        };

        internal static readonly string[] MachineGuns = {
            "WEAPON_MG",
            "WEAPON_COMBATMG",
            "WEAPON_COMBATMG_MK2",
            "WEAPON_GUSENBERG",
        };

        internal static readonly string[] Snipers = {
            "WEAPON_SNIPERRIFLE",
            "WEAPON_HEAVYSNIPER",
            "WEAPON_HEAVYSNIPER_MK2",
            "WEAPON_MARKSMANRIFLE",
            "WEAPON_MARKSMANRIFLE_MK2",
            "WEAPON_PRECISIONRIFLE",
        };

        internal static readonly string[] Heavy = {
            "WEAPON_RPG",
            "WEAPON_GRENADELAUNCHER",
            "WEAPON_MINIGUN",
            "WEAPON_FIREWORK",
            "WEAPON_RAILGUN",
            "WEAPON_HOMINGLAUNCHER",
            "WEAPON_COMPACTLAUNCHER",
            "WEAPON_RAYMINIGUN",
            "WEAPON_EMPLAUNCHER",
        };

        internal static readonly string[] Melee = {
            "WEAPON_KNIFE",
            "WEAPON_NIGHTSTICK",
            "WEAPON_HAMMER",
            "WEAPON_BAT",
            "WEAPON_GOLFCLUB",
            "WEAPON_CROWBAR",
            "WEAPON_BOTTLE",
            "WEAPON_DAGGER",
            "WEAPON_HATCHET",
            "WEAPON_KNUCKLE",
            "WEAPON_MACHETE",
            "WEAPON_FLASHLIGHT",
            "WEAPON_SWITCHBLADE",
            "WEAPON_POOLCUE",
            "WEAPON_WRENCH",
            "WEAPON_BATTLEAXE",
            "WEAPON_STONE_HATCHET",
        };

        internal static readonly string[] Throwables = {
            "WEAPON_GRENADE",
            "WEAPON_BZGAS",
            "WEAPON_MOLOTOV",
            "WEAPON_STICKYBOMB",
            "WEAPON_PROXMINE",
            "WEAPON_SNOWBALL",
            "WEAPON_PIPEBOMB",
            "WEAPON_BALL",
            "WEAPON_SMOKEGRENADE",
            "WEAPON_FLARE",
        };

        internal static readonly string[] Misc = {
            "WEAPON_PETROLCAN",
            "WEAPON_FIREEXTINGUISHER",
            "WEAPON_HAZARDCAN",
            "WEAPON_FERTILIZERCAN",
            "WEAPON_ACIDPACKAGE",
        };

        internal static readonly Dictionary<string, string> DisplayNames = new Dictionary<string, string>
        {
            { "WEAPON_PISTOL", "Pistol" },
            { "WEAPON_PISTOL_MK2", "Pistol Mk II" },
            { "WEAPON_COMBATPISTOL", "Combat Pistol" },
            { "WEAPON_APPISTOL", "AP Pistol" },
            { "WEAPON_STUNGUN", "Stun Gun" },
            { "WEAPON_PISTOL50", "Pistol .50" },
            { "WEAPON_SNSPISTOL", "SNS Pistol" },
            { "WEAPON_SNSPISTOL_MK2", "SNS Pistol Mk II" },
            { "WEAPON_HEAVYPISTOL", "Heavy Pistol" },
            { "WEAPON_VINTAGEPISTOL", "Vintage Pistol" },
            { "WEAPON_FLAREGUN", "Flare Gun" },
            { "WEAPON_MARKSMANPISTOL", "Marksman Pistol" },
            { "WEAPON_REVOLVER", "Heavy Revolver" },
            { "WEAPON_REVOLVER_MK2", "Heavy Revolver Mk II" },
            { "WEAPON_DOUBLEACTION", "Double-Action Revolver" },
            { "WEAPON_RAYPISTOL", "Up-n-Atomizer" },
            { "WEAPON_CERAMICPISTOL", "Ceramic Pistol" },
            { "WEAPON_NAVYREVOLVER", "Navy Revolver" },
            { "WEAPON_GADGETPISTOL", "Perico Pistol" },
            { "WEAPON_MICROSMG", "Micro SMG" },
            { "WEAPON_SMG", "SMG" },
            { "WEAPON_SMG_MK2", "SMG Mk II" },
            { "WEAPON_ASSAULTSMG", "Assault SMG" },
            { "WEAPON_COMBATPDW", "Combat PDW" },
            { "WEAPON_MACHINEPISTOL", "Machine Pistol" },
            { "WEAPON_MINISMG", "Mini SMG" },
            { "WEAPON_RAYCARBINE", "Unholy Hellbringer" },
            { "WEAPON_PUMPSHOTGUN", "Pump Shotgun" },
            { "WEAPON_PUMPSHOTGUN_MK2", "Pump Shotgun Mk II" },
            { "WEAPON_SAWNOFFSHOTGUN", "Sawed-Off Shotgun" },
            { "WEAPON_ASSAULTSHOTGUN", "Assault Shotgun" },
            { "WEAPON_BULLPUPSHOTGUN", "Bullpup Shotgun" },
            { "WEAPON_MUSKET", "Musket" },
            { "WEAPON_HEAVYSHOTGUN", "Heavy Shotgun" },
            { "WEAPON_DBSHOTGUN", "Double Barrel Shotgun" },
            { "WEAPON_AUTOSHOTGUN", "Sweeper Shotgun" },
            { "WEAPON_COMBATSHOTGUN", "Combat Shotgun" },
            { "WEAPON_ASSAULTRIFLE", "Assault Rifle" },
            { "WEAPON_ASSAULTRIFLE_MK2", "Assault Rifle Mk II" },
            { "WEAPON_CARBINERIFLE", "Carbine Rifle" },
            { "WEAPON_CARBINERIFLE_MK2", "Carbine Rifle Mk II" },
            { "WEAPON_ADVANCEDRIFLE", "Advanced Rifle" },
            { "WEAPON_SPECIALCARBINE", "Special Carbine" },
            { "WEAPON_SPECIALCARBINE_MK2", "Special Carbine Mk II" },
            { "WEAPON_BULLPUPRIFLE", "Bullpup Rifle" },
            { "WEAPON_BULLPUPRIFLE_MK2", "Bullpup Rifle Mk II" },
            { "WEAPON_COMPACTRIFLE", "Compact Rifle" },
            { "WEAPON_MILITARYRIFLE", "Military Rifle" },
            { "WEAPON_HEAVYRIFLE", "Heavy Rifle" },
            { "WEAPON_TACTICALRIFLE", "Service Carbine" },
            { "WEAPON_MG", "MG" },
            { "WEAPON_COMBATMG", "Combat MG" },
            { "WEAPON_COMBATMG_MK2", "Combat MG Mk II" },
            { "WEAPON_GUSENBERG", "Gusenberg Sweeper" },
            { "WEAPON_SNIPERRIFLE", "Sniper Rifle" },
            { "WEAPON_HEAVYSNIPER", "Heavy Sniper" },
            { "WEAPON_HEAVYSNIPER_MK2", "Heavy Sniper Mk II" },
            { "WEAPON_MARKSMANRIFLE", "Marksman Rifle" },
            { "WEAPON_MARKSMANRIFLE_MK2", "Marksman Rifle Mk II" },
            { "WEAPON_PRECISIONRIFLE", "Precision Rifle" },
            { "WEAPON_RPG", "RPG" },
            { "WEAPON_GRENADELAUNCHER", "Grenade Launcher" },
            { "WEAPON_MINIGUN", "Minigun" },
            { "WEAPON_FIREWORK", "Firework Launcher" },
            { "WEAPON_RAILGUN", "Railgun" },
            { "WEAPON_HOMINGLAUNCHER", "Homing Launcher" },
            { "WEAPON_COMPACTLAUNCHER", "Compact Grenade Launcher" },
            { "WEAPON_RAYMINIGUN", "Widowmaker" },
            { "WEAPON_EMPLAUNCHER", "EMP Launcher" },
            { "WEAPON_KNIFE", "Knife" },
            { "WEAPON_NIGHTSTICK", "Nightstick" },
            { "WEAPON_HAMMER", "Hammer" },
            { "WEAPON_BAT", "Baseball Bat" },
            { "WEAPON_GOLFCLUB", "Golf Club" },
            { "WEAPON_CROWBAR", "Crowbar" },
            { "WEAPON_BOTTLE", "Broken Bottle" },
            { "WEAPON_DAGGER", "Antique Cavalry Dagger" },
            { "WEAPON_HATCHET", "Hatchet" },
            { "WEAPON_KNUCKLE", "Knuckle Dusters" },
            { "WEAPON_MACHETE", "Machete" },
            { "WEAPON_FLASHLIGHT", "Flashlight" },
            { "WEAPON_SWITCHBLADE", "Switchblade" },
            { "WEAPON_POOLCUE", "Pool Cue" },
            { "WEAPON_WRENCH", "Pipe Wrench" },
            { "WEAPON_BATTLEAXE", "Battle Axe" },
            { "WEAPON_STONE_HATCHET", "Stone Hatchet" },
            { "WEAPON_GRENADE", "Grenade" },
            { "WEAPON_BZGAS", "BZ Gas" },
            { "WEAPON_MOLOTOV", "Molotov Cocktail" },
            { "WEAPON_STICKYBOMB", "Sticky Bomb" },
            { "WEAPON_PROXMINE", "Proximity Mine" },
            { "WEAPON_SNOWBALL", "Snowball" },
            { "WEAPON_PIPEBOMB", "Pipe Bomb" },
            { "WEAPON_BALL", "Ball" },
            { "WEAPON_SMOKEGRENADE", "Tear Gas" },
            { "WEAPON_FLARE", "Flare" },
            { "WEAPON_PETROLCAN", "Jerry Can" },
            { "WEAPON_FIREEXTINGUISHER", "Fire Extinguisher" },
            { "WEAPON_HAZARDCAN", "Hazardous Jerry Can" },
            { "WEAPON_FERTILIZERCAN", "Fertilizer Can" },
            { "WEAPON_ACIDPACKAGE", "Acid Package" },
        };

        internal static readonly Dictionary<string, int> Prices = new Dictionary<string, int>
        {
            { "WEAPON_PISTOL", 500 },
            { "WEAPON_PISTOL_MK2", 73750 },
            { "WEAPON_COMBATPISTOL", 5000 },
            { "WEAPON_APPISTOL", 5000 },
            { "WEAPON_STUNGUN", 500 },
            { "WEAPON_PISTOL50", 3000 },
            { "WEAPON_SNSPISTOL", 2750 },
            { "WEAPON_SNSPISTOL_MK2", 97500 },
            { "WEAPON_HEAVYPISTOL", 3750 },
            { "WEAPON_VINTAGEPISTOL", 3450 },
            { "WEAPON_FLAREGUN", 5750 },
            { "WEAPON_MARKSMANPISTOL", 4350 },
            { "WEAPON_REVOLVER", 5400 },
            { "WEAPON_REVOLVER_MK2", 149000 },
            { "WEAPON_DOUBLEACTION", 12500 },
            { "WEAPON_RAYPISTOL", 399000 },
            { "WEAPON_CERAMICPISTOL", 20000 },
            { "WEAPON_NAVYREVOLVER", 15200 },
            { "WEAPON_GADGETPISTOL", 17500 },
            { "WEAPON_MICROSMG", 1500 },
            { "WEAPON_SMG", 7500 },
            { "WEAPON_SMG_MK2", 85000 },
            { "WEAPON_ASSAULTSMG", 12000 },
            { "WEAPON_COMBATPDW", 12175 },
            { "WEAPON_MACHINEPISTOL", 6250 },
            { "WEAPON_MINISMG", 8900 },
            { "WEAPON_RAYCARBINE", 449000 },
            { "WEAPON_PUMPSHOTGUN", 2000 },
            { "WEAPON_PUMPSHOTGUN_MK2", 82500 },
            { "WEAPON_SAWNOFFSHOTGUN", 3000 },
            { "WEAPON_ASSAULTSHOTGUN", 10000 },
            { "WEAPON_BULLPUPSHOTGUN", 8000 },
            { "WEAPON_MUSKET", 21400 },
            { "WEAPON_HEAVYSHOTGUN", 13550 },
            { "WEAPON_DBSHOTGUN", 15450 },
            { "WEAPON_AUTOSHOTGUN", 14900 },
            { "WEAPON_COMBATSHOTGUN", 295000 },
            { "WEAPON_ASSAULTRIFLE", 5000 },
            { "WEAPON_ASSAULTRIFLE_MK2", 98750 },
            { "WEAPON_CARBINERIFLE", 13000 },
            { "WEAPON_CARBINERIFLE_MK2", 107500 },
            { "WEAPON_ADVANCEDRIFLE", 14250 },
            { "WEAPON_SPECIALCARBINE", 14750 },
            { "WEAPON_SPECIALCARBINE_MK2", 135000 },
            { "WEAPON_BULLPUPRIFLE", 14500 },
            { "WEAPON_BULLPUPRIFLE_MK2", 105750 },
            { "WEAPON_COMPACTRIFLE", 14650 },
            { "WEAPON_MILITARYRIFLE", 395000 },
            { "WEAPON_HEAVYRIFLE", 430500 },
            { "WEAPON_TACTICALRIFLE", 405000 },
            { "WEAPON_MG", 9000 },
            { "WEAPON_COMBATMG", 15000 },
            { "WEAPON_COMBATMG_MK2", 119000 },
            { "WEAPON_GUSENBERG", 14600 },
            { "WEAPON_SNIPERRIFLE", 20000 },
            { "WEAPON_HEAVYSNIPER", 38150 },
            { "WEAPON_HEAVYSNIPER_MK2", 165375 },
            { "WEAPON_MARKSMANRIFLE", 15750 },
            { "WEAPON_MARKSMANRIFLE_MK2", 149000 },
            { "WEAPON_PRECISIONRIFLE", 450000 },
            { "WEAPON_RPG", 26250 },
            { "WEAPON_GRENADELAUNCHER", 32400 },
            { "WEAPON_MINIGUN", 50000 },
            { "WEAPON_FIREWORK", 60000 },
            { "WEAPON_RAILGUN", 250000 },
            { "WEAPON_HOMINGLAUNCHER", 75000 },
            { "WEAPON_COMPACTLAUNCHER", 45900 },
            { "WEAPON_RAYMINIGUN", 499000 },
            { "WEAPON_EMPLAUNCHER", 325000 },
            { "WEAPON_KNIFE", 50 },
            { "WEAPON_NIGHTSTICK", 50 },
            { "WEAPON_HAMMER", 50 },
            { "WEAPON_BAT", 50 },
            { "WEAPON_GOLFCLUB", 75 },
            { "WEAPON_CROWBAR", 50 },
            { "WEAPON_BOTTLE", 50 },
            { "WEAPON_DAGGER", 2000 },
            { "WEAPON_HATCHET", 75 },
            { "WEAPON_KNUCKLE", 100 },
            { "WEAPON_MACHETE", 100 },
            { "WEAPON_FLASHLIGHT", 50 },
            { "WEAPON_SWITCHBLADE", 1950 },
            { "WEAPON_POOLCUE", 50 },
            { "WEAPON_WRENCH", 75 },
            { "WEAPON_BATTLEAXE", 100 },
            { "WEAPON_STONE_HATCHET", 100 },
            { "WEAPON_GRENADE", 250 },
            { "WEAPON_BZGAS", 150 },
            { "WEAPON_MOLOTOV", 200 },
            { "WEAPON_STICKYBOMB", 600 },
            { "WEAPON_PROXMINE", 1000 },
            { "WEAPON_SNOWBALL", 50 },
            { "WEAPON_PIPEBOMB", 750 },
            { "WEAPON_BALL", 50 },
            { "WEAPON_SMOKEGRENADE", 150 },
            { "WEAPON_FLARE", 50 },
            { "WEAPON_PETROLCAN", 100 },
            { "WEAPON_FIREEXTINGUISHER", 100 },
            { "WEAPON_HAZARDCAN", 150 },
            { "WEAPON_FERTILIZERCAN", 150 },
            { "WEAPON_ACIDPACKAGE", 250 },
        };

        internal static readonly Dictionary<string, string> CategoryNames = new Dictionary<string, string>
        {
            { "WEAPON_PISTOL", "Pistols" },
            { "WEAPON_PISTOL_MK2", "Pistols" },
            { "WEAPON_COMBATPISTOL", "Pistols" },
            { "WEAPON_APPISTOL", "Pistols" },
            { "WEAPON_STUNGUN", "Pistols" },
            { "WEAPON_PISTOL50", "Pistols" },
            { "WEAPON_SNSPISTOL", "Pistols" },
            { "WEAPON_SNSPISTOL_MK2", "Pistols" },
            { "WEAPON_HEAVYPISTOL", "Pistols" },
            { "WEAPON_VINTAGEPISTOL", "Pistols" },
            { "WEAPON_FLAREGUN", "Pistols" },
            { "WEAPON_MARKSMANPISTOL", "Pistols" },
            { "WEAPON_REVOLVER", "Pistols" },
            { "WEAPON_REVOLVER_MK2", "Pistols" },
            { "WEAPON_DOUBLEACTION", "Pistols" },
            { "WEAPON_RAYPISTOL", "Pistols" },
            { "WEAPON_CERAMICPISTOL", "Pistols" },
            { "WEAPON_NAVYREVOLVER", "Pistols" },
            { "WEAPON_GADGETPISTOL", "Pistols" },
            { "WEAPON_MICROSMG", "SMGs" },
            { "WEAPON_SMG", "SMGs" },
            { "WEAPON_SMG_MK2", "SMGs" },
            { "WEAPON_ASSAULTSMG", "SMGs" },
            { "WEAPON_COMBATPDW", "SMGs" },
            { "WEAPON_MACHINEPISTOL", "SMGs" },
            { "WEAPON_MINISMG", "SMGs" },
            { "WEAPON_RAYCARBINE", "SMGs" },
            { "WEAPON_PUMPSHOTGUN", "Shotguns" },
            { "WEAPON_PUMPSHOTGUN_MK2", "Shotguns" },
            { "WEAPON_SAWNOFFSHOTGUN", "Shotguns" },
            { "WEAPON_ASSAULTSHOTGUN", "Shotguns" },
            { "WEAPON_BULLPUPSHOTGUN", "Shotguns" },
            { "WEAPON_MUSKET", "Shotguns" },
            { "WEAPON_HEAVYSHOTGUN", "Shotguns" },
            { "WEAPON_DBSHOTGUN", "Shotguns" },
            { "WEAPON_AUTOSHOTGUN", "Shotguns" },
            { "WEAPON_COMBATSHOTGUN", "Shotguns" },
            { "WEAPON_ASSAULTRIFLE", "Assault Rifles" },
            { "WEAPON_ASSAULTRIFLE_MK2", "Assault Rifles" },
            { "WEAPON_CARBINERIFLE", "Assault Rifles" },
            { "WEAPON_CARBINERIFLE_MK2", "Assault Rifles" },
            { "WEAPON_ADVANCEDRIFLE", "Assault Rifles" },
            { "WEAPON_SPECIALCARBINE", "Assault Rifles" },
            { "WEAPON_SPECIALCARBINE_MK2", "Assault Rifles" },
            { "WEAPON_BULLPUPRIFLE", "Assault Rifles" },
            { "WEAPON_BULLPUPRIFLE_MK2", "Assault Rifles" },
            { "WEAPON_COMPACTRIFLE", "Assault Rifles" },
            { "WEAPON_MILITARYRIFLE", "Assault Rifles" },
            { "WEAPON_HEAVYRIFLE", "Assault Rifles" },
            { "WEAPON_TACTICALRIFLE", "Assault Rifles" },
            { "WEAPON_MG", "Machine Guns" },
            { "WEAPON_COMBATMG", "Machine Guns" },
            { "WEAPON_COMBATMG_MK2", "Machine Guns" },
            { "WEAPON_GUSENBERG", "Machine Guns" },
            { "WEAPON_SNIPERRIFLE", "Sniper Rifles" },
            { "WEAPON_HEAVYSNIPER", "Sniper Rifles" },
            { "WEAPON_HEAVYSNIPER_MK2", "Sniper Rifles" },
            { "WEAPON_MARKSMANRIFLE", "Sniper Rifles" },
            { "WEAPON_MARKSMANRIFLE_MK2", "Sniper Rifles" },
            { "WEAPON_PRECISIONRIFLE", "Sniper Rifles" },
            { "WEAPON_RPG", "Heavy Weapons" },
            { "WEAPON_GRENADELAUNCHER", "Heavy Weapons" },
            { "WEAPON_MINIGUN", "Heavy Weapons" },
            { "WEAPON_FIREWORK", "Heavy Weapons" },
            { "WEAPON_RAILGUN", "Heavy Weapons" },
            { "WEAPON_HOMINGLAUNCHER", "Heavy Weapons" },
            { "WEAPON_COMPACTLAUNCHER", "Heavy Weapons" },
            { "WEAPON_RAYMINIGUN", "Heavy Weapons" },
            { "WEAPON_EMPLAUNCHER", "Heavy Weapons" },
            { "WEAPON_KNIFE", "Melee" },
            { "WEAPON_NIGHTSTICK", "Melee" },
            { "WEAPON_HAMMER", "Melee" },
            { "WEAPON_BAT", "Melee" },
            { "WEAPON_GOLFCLUB", "Melee" },
            { "WEAPON_CROWBAR", "Melee" },
            { "WEAPON_BOTTLE", "Melee" },
            { "WEAPON_DAGGER", "Melee" },
            { "WEAPON_HATCHET", "Melee" },
            { "WEAPON_KNUCKLE", "Melee" },
            { "WEAPON_MACHETE", "Melee" },
            { "WEAPON_FLASHLIGHT", "Melee" },
            { "WEAPON_SWITCHBLADE", "Melee" },
            { "WEAPON_POOLCUE", "Melee" },
            { "WEAPON_WRENCH", "Melee" },
            { "WEAPON_BATTLEAXE", "Melee" },
            { "WEAPON_STONE_HATCHET", "Melee" },
            { "WEAPON_GRENADE", "Throwables" },
            { "WEAPON_BZGAS", "Throwables" },
            { "WEAPON_MOLOTOV", "Throwables" },
            { "WEAPON_STICKYBOMB", "Throwables" },
            { "WEAPON_PROXMINE", "Throwables" },
            { "WEAPON_SNOWBALL", "Throwables" },
            { "WEAPON_PIPEBOMB", "Throwables" },
            { "WEAPON_BALL", "Throwables" },
            { "WEAPON_SMOKEGRENADE", "Throwables" },
            { "WEAPON_FLARE", "Throwables" },
            { "WEAPON_PETROLCAN", "Miscellaneous" },
            { "WEAPON_FIREEXTINGUISHER", "Miscellaneous" },
            { "WEAPON_HAZARDCAN", "Miscellaneous" },
            { "WEAPON_FERTILIZERCAN", "Miscellaneous" },
            { "WEAPON_ACIDPACKAGE", "Miscellaneous" },
        };

        internal static readonly Dictionary<string, int> AmmoCostPerRound = new Dictionary<string, int>
        {
            { "WEAPON_PISTOL", 2 },
            { "WEAPON_PISTOL_MK2", 2 },
            { "WEAPON_COMBATPISTOL", 2 },
            { "WEAPON_APPISTOL", 2 },
            { "WEAPON_STUNGUN", 2 },
            { "WEAPON_PISTOL50", 2 },
            { "WEAPON_SNSPISTOL", 2 },
            { "WEAPON_SNSPISTOL_MK2", 2 },
            { "WEAPON_HEAVYPISTOL", 2 },
            { "WEAPON_VINTAGEPISTOL", 2 },
            { "WEAPON_FLAREGUN", 2 },
            { "WEAPON_MARKSMANPISTOL", 2 },
            { "WEAPON_REVOLVER", 2 },
            { "WEAPON_REVOLVER_MK2", 2 },
            { "WEAPON_DOUBLEACTION", 2 },
            { "WEAPON_RAYPISTOL", 2 },
            { "WEAPON_CERAMICPISTOL", 2 },
            { "WEAPON_NAVYREVOLVER", 2 },
            { "WEAPON_GADGETPISTOL", 2 },
            { "WEAPON_MICROSMG", 2 },
            { "WEAPON_SMG", 2 },
            { "WEAPON_SMG_MK2", 2 },
            { "WEAPON_ASSAULTSMG", 2 },
            { "WEAPON_COMBATPDW", 2 },
            { "WEAPON_MACHINEPISTOL", 2 },
            { "WEAPON_MINISMG", 2 },
            { "WEAPON_RAYCARBINE", 2 },
            { "WEAPON_PUMPSHOTGUN", 5 },
            { "WEAPON_PUMPSHOTGUN_MK2", 5 },
            { "WEAPON_SAWNOFFSHOTGUN", 5 },
            { "WEAPON_ASSAULTSHOTGUN", 5 },
            { "WEAPON_BULLPUPSHOTGUN", 5 },
            { "WEAPON_MUSKET", 5 },
            { "WEAPON_HEAVYSHOTGUN", 5 },
            { "WEAPON_DBSHOTGUN", 5 },
            { "WEAPON_AUTOSHOTGUN", 5 },
            { "WEAPON_COMBATSHOTGUN", 5 },
            { "WEAPON_ASSAULTRIFLE", 3 },
            { "WEAPON_ASSAULTRIFLE_MK2", 3 },
            { "WEAPON_CARBINERIFLE", 3 },
            { "WEAPON_CARBINERIFLE_MK2", 3 },
            { "WEAPON_ADVANCEDRIFLE", 3 },
            { "WEAPON_SPECIALCARBINE", 3 },
            { "WEAPON_SPECIALCARBINE_MK2", 3 },
            { "WEAPON_BULLPUPRIFLE", 3 },
            { "WEAPON_BULLPUPRIFLE_MK2", 3 },
            { "WEAPON_COMPACTRIFLE", 3 },
            { "WEAPON_MILITARYRIFLE", 3 },
            { "WEAPON_HEAVYRIFLE", 3 },
            { "WEAPON_TACTICALRIFLE", 3 },
            { "WEAPON_MG", 3 },
            { "WEAPON_COMBATMG", 3 },
            { "WEAPON_COMBATMG_MK2", 3 },
            { "WEAPON_GUSENBERG", 3 },
            { "WEAPON_SNIPERRIFLE", 10 },
            { "WEAPON_HEAVYSNIPER", 10 },
            { "WEAPON_HEAVYSNIPER_MK2", 10 },
            { "WEAPON_MARKSMANRIFLE", 10 },
            { "WEAPON_MARKSMANRIFLE_MK2", 10 },
            { "WEAPON_PRECISIONRIFLE", 10 },
            { "WEAPON_RPG", 100 },
            { "WEAPON_GRENADELAUNCHER", 100 },
            { "WEAPON_MINIGUN", 100 },
            { "WEAPON_FIREWORK", 100 },
            { "WEAPON_RAILGUN", 100 },
            { "WEAPON_HOMINGLAUNCHER", 100 },
            { "WEAPON_COMPACTLAUNCHER", 100 },
            { "WEAPON_RAYMINIGUN", 100 },
            { "WEAPON_EMPLAUNCHER", 100 },
            { "WEAPON_KNIFE", 0 },
            { "WEAPON_NIGHTSTICK", 0 },
            { "WEAPON_HAMMER", 0 },
            { "WEAPON_BAT", 0 },
            { "WEAPON_GOLFCLUB", 0 },
            { "WEAPON_CROWBAR", 0 },
            { "WEAPON_BOTTLE", 0 },
            { "WEAPON_DAGGER", 0 },
            { "WEAPON_HATCHET", 0 },
            { "WEAPON_KNUCKLE", 0 },
            { "WEAPON_MACHETE", 0 },
            { "WEAPON_FLASHLIGHT", 0 },
            { "WEAPON_SWITCHBLADE", 0 },
            { "WEAPON_POOLCUE", 0 },
            { "WEAPON_WRENCH", 0 },
            { "WEAPON_BATTLEAXE", 0 },
            { "WEAPON_STONE_HATCHET", 0 },
            { "WEAPON_GRENADE", 50 },
            { "WEAPON_BZGAS", 50 },
            { "WEAPON_MOLOTOV", 50 },
            { "WEAPON_STICKYBOMB", 50 },
            { "WEAPON_PROXMINE", 50 },
            { "WEAPON_SNOWBALL", 50 },
            { "WEAPON_PIPEBOMB", 50 },
            { "WEAPON_BALL", 50 },
            { "WEAPON_SMOKEGRENADE", 50 },
            { "WEAPON_FLARE", 50 },
            { "WEAPON_PETROLCAN", 0 },
            { "WEAPON_FIREEXTINGUISHER", 0 },
            { "WEAPON_HAZARDCAN", 0 },
            { "WEAPON_FERTILIZERCAN", 0 },
            { "WEAPON_ACIDPACKAGE", 0 },
        };
    }
}
