<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>ALLIN1</AssemblyName>
    <RootNamespace>ALLIN1</RootNamespace>
    <OutputType>Library</OutputType>
    <PlatformTarget>x64</PlatformTarget>
    <LangVersion>9.0</LangVersion>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="tools\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ScriptHookVDotNet3" Version="3.6.0" />
    <PackageReference Include="LemonUI.SHVDN3" Version="2.2.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Windows.Forms" />
  </ItemGroup>

</Project>
